#!/usr/bin/env -S python -u

# This script takes .feather files generated by UrbanPop, including both person details and daytime-nightime assignments, and
# converts them into a csv file with the information that is needed for ExaEpi.
# This script also generates a c++ header file containing the structure of the data, including functions for reading and writing
# the data.

import sys
import os
import gc
import psutil
import pandas as pd
from pandas.api.types import CategoricalDtype
import numpy as np
import argparse
import configparser
import glob
import geopandas
import io
from colorama import Fore
from get_schools import timer

# only include these fields in the output csv and c++ structure

include_fields = [
    "p_id",
    "h_id",
    "geoid",
    "pr_age",
    "pr_sex",
    "pr_race",
    "pr_travel",
    "pr_veh_occ",
    "role",
    "naics",
    "grade",
    "school_id",
]

# note: missing category indexes are written as -1
# we could extract these from the dataset, but then they will not be in a suitable order, even with sorting
# so we predefine and check for values in the data that are not listed here
categ_types = {
    "hh_type": CategoricalDtype(categories=["hh", "gq"]),
    "hh_living_arrangement": CategoricalDtype(categories=["married", "male_no_spouse", "female_no_spouse", "alone", "not_alone"]),
    "hh_has_kids": CategoricalDtype(categories=["no", "yes"]),
    "hh_dwg": CategoricalDtype(
        categories=[
            "single_fam_detach",
            "single_fam_attach",
            "2_unit",
            "3_4_unit",
            "5_9_unit",
            "10_19_unit",
            "20_49_unit",
            "GE50_unit",
            "mob_home",
            "other",
        ]
    ),
    "hh_tenure": CategoricalDtype(categories=["own", "rent", "other"]),
    "hh_vehicles": CategoricalDtype(categories=["01", "02", "03", "04", "05", "GE06"]),
    "pr_sex": CategoricalDtype(categories=["female", "male"]),
    "pr_race": CategoricalDtype(categories=["white", "blk_af_amer", "asian", "native_amer", "pac_island", "other", "mult"]),
    "pr_hsplat": CategoricalDtype(categories=["no", "yes"]),
    "pr_ipr": CategoricalDtype(categories=["L050", "050_099", "100_124", "125_149", "150_184", "185_199", "GE200"]),
    "pr_emp_stat": CategoricalDtype(categories=["not.in.force", "unemp", "employed", "mil"]),
    "pr_travel": CategoricalDtype(
        categories=["car_truck_van", "public_transportation", "bicycle", "walked", "motorcycle", "taxicab", "other", "wfh"]
    ),
    "pr_veh_occ": CategoricalDtype(categories=["drove_alone", "carpooled"]),
    "pr_grade": CategoricalDtype(
        categories=[
            "childcare",
            "preschl",
            "kind",
            "1st",
            "2nd",
            "3rd",
            "4th",
            "5th",
            "6th",
            "7th",
            "8th",
            "9th",
            "10th",
            "11th",
            "12th",
            "undergrad",
            "grad",
        ]
    ),
    "role": CategoricalDtype(categories=["nope", "worker", "student"]),
    "naics": CategoricalDtype(
        categories=[
            "111",
            "112",
            "113",
            "1133",
            "114",
            "115",
            "211",
            "2121",
            "2122",
            "2123",
            "213",
            "22",
            "221",
            "2211",
            "2212",
            "2213",
            "22132",
            "23",
            "3",
            "31",
            "311",
            "3113",
            "3114",
            "3115",
            "3116",
            "3118",
            "311811",
            "3121",
            "3122",
            "3131",
            "3132",
            "3133",
            "314",
            "31411",
            "315",
            "316",
            "3162",
            "3211",
            "3212",
            "3219",
            "32199",
            "3221",
            "3222",
            "32221",
            "3231",
            "3241",
            "32411",
            "325",
            "3252",
            "3253",
            "3254",
            "3255",
            "3256",
            "3261",
            "3262",
            "32621",
            "327",
            "32711",
            "327120",
            "3272",
            "3279",
            "33",
            "331",
            "3313",
            "3314",
            "3315",
            "332",
            "3321",
            "3322",
            "3327",
            "3328",
            "33299",
            "333",
            "3331",
            "33311",
            "3333",
            "3335",
            "3336",
            "334",
            "3341",
            "3345",
            "335",
            "3352",
            "336",
            "33641",
            "3365",
            "3366",
            "3369",
            "337",
            "3391",
            "3399",
            "4",
            "42",
            "4231",
            "4232",
            "4233",
            "4234",
            "4235",
            "4236",
            "4237",
            "4238",
            "4239",
            "42393",
            "424",
            "4241",
            "4243",
            "4244",
            "4245",
            "4247",
            "4248",
            "4249",
            "42491",
            "4251",
            "4411",
            "4412",
            "4413",
            "442",
            "443141",
            "443142",
            "4441",
            "44413",
            "4442",
            "44511",
            "44512",
            "4452",
            "4453",
            "446",
            "44611",
            "447",
            "4481",
            "44821",
            "4483",
            "4511",
            "45113",
            "45114",
            "45121",
            "45221",
            "4523",
            "4531",
            "45321",
            "45322",
            "4533",
            "4539",
            "454110",
            "4542",
            "454310",
            "45439",
            "481",
            "482",
            "483",
            "484",
            "485",
            "4853",
            "486",
            "487",
            "488",
            "491",
            "492",
            "493",
            "5111",
            "51111",
            "5112",
            "5121",
            "5122",
            "515",
            "517",
            "517311",
            "5182",
            "5191",
            "51912",
            "51913",
            "52",
            "522",
            "5221",
            "5241",
            "5242",
            "53",
            "531",
            "5313",
            "532",
            "5321",
            "5411",
            "5412",
            "5413",
            "5414",
            "5415",
            "5416",
            "5417",
            "5418",
            "5419",
            "54194",
            "55",
            "561",
            "5613",
            "5614",
            "5615",
            "5616",
            "5617",
            "56173",
            "562",
            "611",
            "6111",
            "621",
            "6211",
            "6212",
            "6213",
            "62131",
            "62132",
            "6214",
            "6216",
            "622",
            "6222",
            "623",
            "6231",
            "6241",
            "6242",
            "6243",
            "6244",
            "711",
            "7111",
            "7112",
            "7115",
            "712",
            "713",
            "71395",
            "721",
            "7211",
            "722",
            "7224",
            "8111",
            "811192",
            "8112",
            "8113",
            "8114",
            "8121",
            "812111",
            "812112",
            "8122",
            "8123",
            "8129",
            "813",
            "8131",
            "8139",
            "81393",
            "814",
            "92",
            "9211",
            "92113",
            "92119",
            "923",
            "928",
        ]
    ),
    # "naics": CategoricalDtype(  # 2017 - latest
    #    categories=[
    #        "agr_ffh",  # 0 Agriculture, forestry, fishing and hunting
    #        "ext",  # 1 Mining, quarrying, and oil and gas extraction
    #        "utl",  # 2 Utilities
    #        "con",  # 3 Construction
    #        "mfg",  # 4 Manufacturing
    #        "whl",  # 5 Wholesale trade
    #        "ret",  # 6 Retail trade
    #        "trn_whs",  # 7 Transportation and warehousing
    #        "inf",  # 8 Information
    #        "fin_ins",  # 9 Finance and insurance
    #        "rrl",  # 10 Real estate rental and leasing
    #        "prf",  # 11 Professional, scientific and technical services
    #        "mgt",  # 12 Management of companies and enterprises
    #        "adm_wmr",  # 13 Administrative and support and waste management and remediating services
    #        "edu",  # 14 Educational services
    #        "med_sca",  # 15 Health care and social services
    #        "ent",  # 16 Arts, entertainment and recreation
    #        "afs",  # 17 Accomodation and food services
    #        "srv",  # 18 Other services (except public administration)
    #        "pad",  # 19 Public administration
    #        "wfh",  # 20 Work from home
    #    ]
    # ),
}

DUMP_INTERMEDIATES = False


def print_header(df):
    hdr_fname = "UrbanPopAgentStruct.H"
    print("Writing C++ header file at", hdr_fname)

    hdr = f"""
/*! @file {hdr_fname}
    \\brief Contains #UrbanPopAgent class used for reading in UrbanPop data
    File automatically generated by UrbanPop-scripts/extract_urbanpop_feather.py
*/

#pragma once

#include <stdlib.h>
#include <string.h>
#include <fstream>
#include <sstream>

using std::string;
using float32_t = amrex::ParticleReal;

namespace UrbanPop {{

const size_t NUM_COLS = {len(df.columns)};

"""
    # """

    # print out string arrays with category names
    for field_type in df:
        if field_type in categ_types:
            categs_expected = list(categ_types[field_type].categories)
            num_categs = len(categs_expected)
            hdr += f"""const int {field_type.upper()}_COUNT = {num_categs};\n"""
            hdr += f"""static string {field_type}_descriptions[{field_type.upper()}_COUNT] = {{"{'", "'.join(categs_expected)}"}};\n"""
            # ensure it works even for numbers in the categories
            categs_expected = ["_" + categ for categ in categs_expected]
            hdr += f"""struct {field_type.upper()} {{ enum {{{', '.join(categs_expected)}}}; }};\n"""
    hdr += "\n"

    hdr += """
static std::vector<string> splitString(const string &s, char delim) {
    std::vector<string> elems;
    std::stringstream ss(s);
    string item;
    while (std::getline(ss, item, delim)) elems.push_back(item);
    return elems;
}

"""

    hdr += "struct UrbanPopAgent {\n"
    for i, col in enumerate(df.columns):
        hdr += f"""    {df.dtypes.iloc[i]}_t {col};\n"""

    hdr += """
    bool readCsv(std::ifstream &f) {
        string buf;
        if (!getline(f, buf)) return false;
        if (buf[0] != '*') {
            id = -1;
            return true;
        }
        try {
            std::vector<string> tokens = splitString(buf.substr(2), ',');
            if (tokens.size() != NUM_COLS)
                throw std::runtime_error("Incorrect number of tokens, expected " + std::to_string(NUM_COLS) +
                                         " got " + std::to_string(tokens.size()));\n"""

    for i, col in enumerate(df.columns):
        if df.dtypes.iloc[i] == "float32":
            hdr += f"""            {col} = stof(tokens[{i}]);\n"""
        elif df.dtypes.iloc[i] == "int64":
            hdr += f"""            {col} = stol(tokens[{i}]);\n"""
        elif df.dtypes.iloc[i] == "string":
            hdr += f"""            {col} = tokens[{i});\n"""
        else:
            hdr += f"""            {col} = stoi(tokens[{i}]);\n"""
    hdr += """
        } catch (const std::exception &ex) {
            std::ostringstream os;
            os << "<" << __LINE__ << ">: Error reading UrbanPop input file: " << ex.what() << ", line read: " << "'" << buf << "'";
            amrex::Abort(os.str());
        }
        return true;
    }\n"""

    hdr += """
    friend std::ostream& operator<<(std::ostream& os, const UrbanPopAgent& agent) {
        os << std::fixed << std::setprecision(6);\n"""

    for i, col in enumerate(df.columns):
        c_type = str(df.dtypes.iloc[i]) + "_t"
        if col in categ_types:
            hdr += (
                "        os << (int)agent."
                + col
                + " << (agent."
                + col
                + ' != -1 ? ":" + '
                + col
                + "_descriptions[agent."
                + col
                + '] : "")'
            )
        else:
            hdr += "        os << " + ("(int)" if c_type == "int8_t" else "") + "agent." + col

        if i < len(df.columns) - 1:
            hdr += ' << ",";\n'
        else:
            hdr += ";"
        # os << (int)agent.hh_dwg << (agent.hh_dwg != -1 ? ":" + hh_dwg_descriptions[agent.hh_dwg] : "") << ",";

    hdr += """
        return os;
    }
};
} // namespace UrbanPop
"""

    f_hdr = open(hdr_fname, "w")
    print(hdr, file=f_hdr)
    f_hdr.close()
    print("Wrote", len(df.columns), "fields to", hdr_fname)


@timer
def process_census_bg_shape_file(fnames):
    geoid_locs_map = {}
    for shape_fname in fnames:
        # don't actually need to compute the centroid because the block group file has it under the INTPTLAT10 and INTPTLON10 cols
        # df = geopandas.read_file(shape_fname, columns=["GEOID10", "INTPTLAT10", "INTPTLON10"])
        # df = df.to_crs(crs=4326)
        # df["centroid"] = df.centroid
        print("Reading shape files at", shape_fname)
        df = geopandas.read_file(shape_fname, columns=["GEOID10", "INTPTLAT10", "INTPTLON10"])[
            ["GEOID10", "INTPTLAT10", "INTPTLON10"]
        ]
        df.GEOID10 = df.GEOID10.astype("int64")
        df.INTPTLAT10 = df.INTPTLAT10.astype("float32")
        df.INTPTLON10 = df.INTPTLON10.astype("float32")
        # df = df[df.GEOID10 != 350130017061]
        # df.to_csv(shape_fname + ".csv", index=False)
        # print("Wrote", len(df.index), "GEOID locations to", shape_fname + ".csv")
        geoid_locs_map.update(df.set_index("GEOID10").T.to_dict("list"))
    print("GEOID to locations map contains", len(geoid_locs_map), "entries")
    return geoid_locs_map


@timer
def process_nt_dt_feather_files(fnames, out_fname):
    dfs = []
    print(f"Reading nt/dt data from {len(fnames)} files")
    for i, fname in enumerate(fnames):
        df_metro = pd.read_feather(fname)
        dfs.append(df_metro)

    df = pd.concat(dfs, ignore_index=True)
    del dfs
    dfs = []
    print(f"Read {len(df.index)} records")
    df.sort_values(by=["p_id"], inplace=True, ignore_index=True)
    df.orig_geoid = df.orig_geoid.astype("int64")
    df.dest_geoid = df.dest_geoid.astype("int64")
    df.naics = df.naics.astype("int32")

    # convert school ids to unique 64 bit ints
    unique_school_ids = sorted(df.school_id.unique(), key=lambda x: (x is None, x))
    school_id_map = dict(zip(unique_school_ids, range(len(unique_school_ids))))
    school_id_map[None] = -1

    df["school_name"] = df["school_id"]
    df["school_id"] = df["school_id"].map(school_id_map).astype("int64")
    # make the valid school ids start at 1, 0 means no school
    df["school_id"] += 1
    # correct students to have only undergrad and grad, not split by male/female
    df.loc[df.grade == "undergrad_female", "grade"] = "undergrad"
    df.loc[df.grade == "undergrad_male", "grade"] = "undergrad"
    df.loc[df.grade == "grad_female", "grade"] = "grad"
    df.loc[df.grade == "grad_male", "grade"] = "grad"

    if DUMP_INTERMEDIATES:
        df.to_csv(out_fname + ".work.csv", sep=",", index=False)

    return df


@timer
def process_pop_feather_files(fnames):
    print(f"Reading UrbanPop data from {len(fnames)} files")
    dfs = []
    df = pd.DataFrame()
    chunk_size = int(len(fnames) / 10)
    for i, fname in enumerate(fnames):
        df_read = pd.read_feather(fname)
        if DUMP_INTERMEDIATES:
            df_read.to_csv(fname + ".csv")
        dfs.append(df_read)
        if i % chunk_size == 0 or i == len(fnames) - 1:
            dfs.append(df)
            df = pd.concat(dfs, ignore_index=True)
            del dfs
            dfs = []
            gc.collect()
            mem_used = float(psutil.Process(os.getpid()).memory_info().rss) / 1024 / 1024 / 1024
            mem_of_df = float(df.memory_usage().sum()) / 1024 / 1024 / 1024
            print(f"  {int(i / chunk_size)}: read {fname}, memory RSS {mem_used:0.2f} G, memory of df {mem_of_df:0.2f} G")
    print(f"Read {len(df.index)} records")
    df.geoid = df.geoid.astype("int64")
    # need to sort to ensure the order is the same between the population files and the daytime/nighttime files
    df.sort_values(by=["p_id"], inplace=True)
    return df


@timer
def get_upop_only(df, nt_dt_df):
    # add rows from UrbanPop data that are missing in the daytime/nighttime data
    merged_df = df.merge(nt_dt_df.drop_duplicates(), on=["p_id"], how="left", indicator=True)
    if DUMP_INTERMEDIATES:
        merged_df.to_csv("merged_df.csv")
    upop_only_df = merged_df[merged_df["_merge"] == "left_only"][
        [
            "p_id",
            "role",
            "geoid",
            "orig_geoid",
            "dest_geoid",
            "naics",
            "grade",
            "school_id",
            "pr_naics",
            "pr_grade",
            "pr_emp_stat",
        ]
    ]
    upop_only_df.orig_geoid = upop_only_df.geoid
    upop_only_df.dest_geoid = upop_only_df.geoid
    upop_only_df.loc[upop_only_df.pr_grade != "", "role"] = "student"
    upop_only_df.loc[(upop_only_df.pr_emp_stat == "employed") & (upop_only_df.role != "student"), "role"] = "worker"
    upop_only_df.loc[(upop_only_df.role != "student") & (upop_only_df.role != "worker"), "role"] = "nope"
    upop_only_df.naics = upop_only_df.pr_naics.str.extract(r"(\d+)").astype("float").fillna(-1).astype("int")
    # upop_only_df.grade = upop_only_df.pr_grade.astype(gen_nt_dt.grade_categs).cat.codes + 3
    # upop_only_df.loc[upop_only_df.grade == 2, "grade"] = -1
    # since none of these have been assigned to schools, the grades should all be -1
    upop_only_df.grade = -1
    upop_only_df.school_id = 0
    # schools have not been allocated for these students, so set all students to role nope
    num_students = len(upop_only_df[upop_only_df.role == "student"])
    upop_only_df.loc[upop_only_df.role == "student", "role"] = "nope"
    print(f"Set {num_students} students not found in NT/DT flows to role 'nope'")
    upop_only_df.drop(columns=["geoid", "pr_naics", "pr_grade", "pr_emp_stat"], inplace=True)
    print(f"Found {len(upop_only_df)} records in UrbanPop data that are not in the daytime/nighttime data")
    nt_dt_df = pd.concat([nt_dt_df, upop_only_df], ignore_index=True)
    nt_dt_df.sort_values(by=["p_id"], inplace=True)
    df.sort_values(by=["p_id"], inplace=True)
    if DUMP_INTERMEDIATES:
        upop_only_df.to_csv("upop_only.csv")
    return df, nt_dt_df


@timer
def merge_nt_dt(df, nt_dt_df):
    if not np.array_equal(df.p_id.values, nt_dt_df.p_id.values):
        df, nt_dt_df = get_upop_only(df, nt_dt_df)
    if not np.array_equal(df.p_id.values, nt_dt_df.p_id.values):
        err_str = f"{Fore.RED}Mismatched p_ids for population vs daytime/nightime{Fore.RESET}"
        raise RuntimeError(err_str)
    if not np.array_equal(df.geoid.values, nt_dt_df.orig_geoid.values):
        print(f"lengths: {len(df.geoid.values)} {len(nt_dt_df.orig_geoid.values)}")
        err_str = f"{Fore.RED}Mismatched geoids for population vs daytime/nightime{Fore.RESET}"
        raise RuntimeError(err_str)

    # remove all columns not found in include list
    cols_to_purge = set(list(df.columns.values)) - set(include_fields)
    df.drop(columns=cols_to_purge, inplace=True)
    df.insert(df.columns.get_loc("geoid") + 1, "work_geoid", int(0))
    # get values from worker data
    df["work_geoid"] = nt_dt_df["dest_geoid"].values
    if not np.array_equal(df.work_geoid.values, nt_dt_df.dest_geoid.values):
        err_str = f"{Fore.RED}Mismatched work geoids for population vs daytime/nightime{Fore.RESET}"
        raise RuntimeError(err_str)
    nt_dt_df.school_id = nt_dt_df.school_id.fillna(0).astype("int")
    nt_dt_df.naics = nt_dt_df.naics.fillna(-1).astype("int")
    for col in ["role", "naics", "grade", "school_id"]:
        df[col] = nt_dt_df[col].values
        if not np.array_equal(df[col].values, nt_dt_df[col].values):
            df.to_csv("err-df.csv", index=False)
            nt_dt_df.to_csv("err-df-dt-nt.csv", index=False)
            err_str = f"{Fore.RED}Mismatched {col} for population vs daytime/nightime{Fore.RESET}"
            raise RuntimeError(err_str)

    # now ensure all empty grades and school ids are set to 0
    df.loc[(df.grade == "") | (df.school_id == ""), "grade"] = "-1"
    df.loc[(df.grade == "-1") | (df.school_id == ""), "school_id"] = 0
    df.grade = df.grade.astype("int")

    if DUMP_INTERMEDIATES:
        df.to_csv("merged.csv")


@timer
def set_types(df):
    # set up the categ_types for NAICS
    # treat the NAICS types as strings for sorting
    df.naics = df.naics.astype("str")
    # get the NAICS types excluding the first entry which should be -1 for no NAICS code
    # naics_types = sorted(list(filter(None, df.naics.unique())))[1:]
    # categ_types["naics"] = CategoricalDtype(categories=naics_types)

    if "hh_income" in include_fields:
        # pack structure by moving int32_t value to before all int8_t values
        df.insert(4, "hh_income", df.pop("hh_income"))
    df.h_id = df.h_id.str.split("-").str[-1].astype("int32")

    for field_type in df:
        if field_type in categ_types:
            # compare the list with the unique to make sure we haven't found anything not in our predefined list
            categs_found = list(df[field_type].unique())
            categs_expected = list(categ_types[field_type].categories)
            missing = [x for x in categs_found if x not in categs_expected and x != "" and x is not None]
            if missing:
                print(f"{Fore.RED}WARNING: Found missing categories for {field_type}: {missing}{Fore.RESET}")
            df[field_type] = df[field_type].astype(categ_types[field_type]).cat.codes
        else:
            if df.dtypes[field_type] == object:
                df[field_type] = df[field_type].astype("string")
            else:
                # this converts all float to int
                max_val = df[field_type].max()
                if max_val < 128:
                    df[field_type] = df[field_type].astype("int8")
                elif max_val < 2**15:
                    df[field_type] = df[field_type].astype("int16")
                elif max_val < 2**31:
                    df[field_type] = df[field_type].astype("int32")
                else:
                    df[field_type] = df[field_type].astype("int64")


@timer
def compute_worker_populations(df):
    class Fake(object):
        def __init__(self, list_obj):
            self.obj = list_obj

    # compute worker populations for each NAICS code
    work_geoids = df.work_geoid.unique()
    naics_types = list(range(len(categ_types["naics"].categories)))
    print(f"Found {len(work_geoids)} unique work GEOIDS and {len(naics_types)} unique NAICS codes")
    work_geoids_df = df.loc[df["role"] == 1].groupby(["work_geoid", "naics"])["naics"].count().reset_index(name="num")
    # work_geoids_df.to_csv("work_geoids.csv")
    # ensure every GEOID has entries for all the NAICS codes, even ones for count 0
    full_naics_df = pd.DataFrame()
    full_naics_df["work_geoid"] = work_geoids
    full_naics_df["naics"] = Fake(naics_types)
    full_naics_df["num"] = 0
    full_naics_df.naics = full_naics_df.naics.apply(lambda x: x.obj)
    full_naics_df = full_naics_df.explode("naics")
    work_geoids_pops_df = work_geoids_df.merge(full_naics_df, on=["work_geoid", "naics"], how="outer").rename(
        columns={"num_x": "num"}
    )
    work_geoids_pops_df.drop(columns="num_y", inplace=True)
    work_geoids_pops_df["num"] = work_geoids_pops_df["num"].fillna(0).astype("int")
    work_geoids_pops_df["naics"] = work_geoids_pops_df["naics"].astype("int")
    # There should be no -1 NAICS - every worker should have a NAICS code
    num_unset_naics = len(work_geoids_pops_df[work_geoids_pops_df.naics == -1])
    if num_unset_naics > 0:
        err_str = f"{Fore.RED}ERROR: found {num_unset_naics} unset NAICS{Fore.RESET}"
        raise RuntimeError(err_str)
    work_geoids_pops_df.drop(work_geoids_pops_df[work_geoids_pops_df.naics == -1].index, inplace=True)
    return work_geoids_pops_df, naics_types


@timer
def print_agents(df, out_fname):
    num_rows = len(df.index)
    # start with a distinct marker so that the file can be read in parallel more easily
    df.index = ["*"] * num_rows
    # print each geoid in turn so we can track the file offsets
    buff = io.StringIO()
    foffsets = []
    home_pops = []
    home_geoids = []
    num_geoids = df.home_geoid.unique()
    step = int(len(num_geoids) / 10)
    out_fname_csv = out_fname + ".csv"
    print("Writing CSV text data to", out_fname_csv)
    for i, (geoid, subset_df) in enumerate(df.groupby("home_geoid")):
        home_geoids.append(geoid)
        if i % step == 0:
            print(f"  GEOID {geoid} {i}", flush=True)
        foffsets.append(buff.tell())
        home_pops.append(len(subset_df))
        subset_df.to_csv(buff, index=True, header=(i == 0))
    out_fname_csv = out_fname + ".csv"
    with open(out_fname_csv, "w") as f:
        print(buff.getvalue(), end="", file=f)
        print(f"Wrote {len(df)} records in {buff.tell()} bytes")
    buff.close()
    return foffsets, home_pops, home_geoids


@timer
def print_index(df, out_fname, foffsets, home_pops, home_geoids):
    work_geoids_pops_df, naics_types = compute_worker_populations(df)
    work_geoids = df.work_geoid.unique()
    step = int(len(work_geoids) / 10)
    out_fname_idx = out_fname + ".idx"
    print("Writing block group indexes to", out_fname_idx)
    with open(out_fname_idx, mode="w") as f:
        naics_descrs = list(categ_types["naics"].categories)
        print("geoid foff h_pop w_pop", " ".join(naics_descrs), file=f)
        # print work-only GEOIDs
        if len(work_geoids) > len(home_geoids):
            only_work_geoids = list(set(work_geoids) - set(home_geoids))
            print(f"Found {len(only_work_geoids)} work-only geoids")
            for geoid in only_work_geoids:
                work_pops = work_geoids_pops_df.loc[work_geoids_pops_df.work_geoid == geoid].num.to_list()
                tot_work_pop = np.sum(work_pops)
                print(geoid, 0, 0, tot_work_pop, " ".join(map(str, work_pops)), file=f)
        for i, geoid in enumerate(home_geoids):
            if i % step == 0:
                print(f"  GEOID {geoid} {i}", flush=True)
            work_pops = work_geoids_pops_df.loc[
                (work_geoids_pops_df.work_geoid == geoid) & (work_geoids_pops_df.naics != "")
            ].num.to_list()
            tot_work_pop = np.sum(work_pops)
            if tot_work_pop == 0:
                work_pops = [0] * len(naics_types)
            if len(work_pops) != len(naics_types):
                err_str = (
                    f"{Fore.RED}ERROR: For geoid {geoid}, work pops != NAICS types, "
                    + f"{len(work_pops)} != {len(naics_types)}{Fore.RESET}"
                )
                for i, p in enumerate(work_pops):
                    if p > 0:
                        print(i, p, naics_descrs[i])
                print("")
                print(f"Total work pop: {sum(work_pops)}")
                raise RuntimeError(err_str)
            print(geoid, foffsets[i], home_pops[i], tot_work_pop, " ".join(map(str, work_pops)), file=f)


def rename_fields(df):
    df.rename(columns={"geoid": "home_geoid"}, inplace=True)
    df.rename(columns={"h_id": "household_id"}, inplace=True)
    df.rename(columns={"p_id": "id"}, inplace=True)
    for col in df.columns:
        if col.startswith("pr_"):
            df.rename(columns={col: col[3:]}, inplace=True)
        elif col.startswith("h_"):
            df.rename(columns={col: "home_" + col[2:]}, inplace=True)
        elif col.startswith("w_"):
            df.rename(columns={col: "work_" + col[2:]}, inplace=True)
        elif col.startswith("hh_"):
            df.rename(columns={col: "household_" + col[3:]}, inplace=True)


@timer
def set_lnglat(df, geoid_locs_map):
    print("Setting lat/long for data")
    # add lat/long locations from geoids
    df.insert(df.columns.get_loc("home_geoid") + 1, "home_lat", float(0))
    df.insert(df.columns.get_loc("home_lat") + 1, "home_lng", float(0))
    df.insert(df.columns.get_loc("work_geoid") + 1, "work_lat", float(0))
    df.insert(df.columns.get_loc("work_lat") + 1, "work_lng", float(0))

    df.home_lat = df.home_lat.astype("float32")
    df.home_lng = df.home_lng.astype("float32")
    df.work_lat = df.work_lat.astype("float32")
    df.work_lng = df.work_lng.astype("float32")
    df.work_geoid = df.work_geoid.astype("int")
    df.home_geoid = df.home_geoid.astype("int")

    # find lat/long for each row entry
    home_locs = df["home_geoid"].map(geoid_locs_map).dropna()
    num_na = len(df) - len(home_locs)
    if num_na > 0:
        print(f"{Fore.RED}WARNING: found {num_na} rows for home locations that were not found in the block groups{Fore.RESET}")
    df["home_lat"] = home_locs.apply(lambda x: x[0]).astype("float32")
    df["home_lng"] = home_locs.apply(lambda x: x[1]).astype("float32")

    work_locs = df["work_geoid"].map(geoid_locs_map).dropna()
    num_na = len(df) - len(work_locs)
    if num_na > 0:
        print(f"{Fore.RED}WARNING: found {num_na} rows for work locations that were not found in the block groups{Fore.RESET}")
    df["work_lat"] = work_locs.apply(lambda x: x[0]).astype("float32")
    df["work_lng"] = work_locs.apply(lambda x: x[1]).astype("float32")

    num_rows = len(df)
    # drop all agents that have no lng/lat values
    df.dropna(subset=["home_lat", "work_lat"], inplace=True)
    num_na = num_rows - len(df)
    if num_na > 0:
        print(f"{Fore.RED}WARNING: dropped {num_na} agents with missing lat/lng coords{Fore.RESET}")

    # df.sort_values(by=["home_lat", "home_lng"], inplace=True)
    if DUMP_INTERMEDIATES:
        df.to_csv("latlng.csv")

    print("Set lat/long for", len(df.index), "agents")


@timer
def adjust_school_ids(df):
    df.loc[df.school_id == 0, "school_id"] = np.nan
    # set school ids to be unique only to work geoid
    df_adjusted = df.groupby(["work_geoid"])["school_id"].transform(lambda x: pd.factorize(x)[0]).astype("int16") + 1
    df["school_id"] = df_adjusted


@timer
def adjust_household_ids(df):
    # set household ids to be unique only to home geoid
    df_adjusted = df.groupby(["home_geoid"])["household_id"].transform(lambda x: pd.factorize(x)[0]).astype("int16")
    df["household_id"] = df_adjusted


@timer
def main():
    np.random.seed(29)

    cfg_parser = argparse.ArgumentParser(description="Convert UrbanPop feather files to C++ struct binary file", add_help=False)
    cfg_parser.add_argument("-c", "--config", help="Config file", metavar="FILE")
    args, remaining_argv = cfg_parser.parse_known_args()
    main_args = {"output": "out", "files": "", "shape_files": "", "day_night_files": ""}
    if args.config:
        cfg = configparser.ConfigParser()
        cfg.read([args.config])
        main_args.update(dict(cfg.items("main")))
        for f in ["files", "shape_files", "day_night_files"]:
            main_args[f] = glob.glob(main_args[f])
    parser = argparse.ArgumentParser(parents=[cfg_parser])
    parser.set_defaults(**main_args)

    parser = argparse.ArgumentParser(parents=[cfg_parser])
    parser.set_defaults(**main_args)
    parser.add_argument("--output", "-o", help="Output file")
    parser.add_argument("--files", "-f", nargs="+", help="Feather files")
    parser.add_argument(
        "--shape_files",
        "-s",
        nargs="+",
        help="Census block group shape files. Available from\n"
        + "https://www.census.gov/cgi-bin/geo/shapefiles/index.php?year=2010&layergroup=Block+Groups",
    )
    parser.add_argument("--day_night_files", "-d", nargs="+", help="Feather files containing daytime and nighttime locations")
    args = parser.parse_args(remaining_argv)
    print(Fore.CYAN, "Options:", sep="")
    for arg, value in args.__dict__.items():
        print(f"  {arg:20s} {value}")
    print(Fore.RESET, end="")

    geoid_locs_map = process_census_bg_shape_file(args.shape_files)
    nt_dt_df = process_nt_dt_feather_files(args.day_night_files, args.output)
    df = process_pop_feather_files(args.files)
    merge_nt_dt(df, nt_dt_df)
    set_types(df)
    rename_fields(df)
    # this call will drop all agents without GEOIDs in the block group shape files
    set_lnglat(df, geoid_locs_map)
    # don't save the lng/lat columns
    df.drop(columns=["home_lng", "home_lat", "work_lng", "work_lat"], inplace=True)
    orig_ids_df = pd.DataFrame()
    orig_ids_df["orig_id"] = df.id
    # make sure all the ids are globally unique and just integers
    df["id"] = np.arange(0, len(df.index))
    orig_ids_df["new_id"] = df.id
    orig_ids_df.to_csv(args.output + ".idmap.csv", index=False)
    print("Fields are:\n", df.dtypes, sep="")
    print_header(df)
    adjust_school_ids(df)
    adjust_household_ids(df)
    foffsets, home_pops, home_geoids = print_agents(df, args.output)
    print_index(df, args.output, foffsets, home_pops, home_geoids)


if __name__ == "__main__":
    main()
