#!/usr/bin/env -S python -u

# This script takes .feather files generated by UrbanPop, including both person details and
# daytime-nightime assignments, and converts them into a csv file with the information that is
# needed for ExaEpi. It can use either daytime/nightime files generated by UrbanPop, or it can
# generate the daytime/nightime flows from LODES and school data. This script also generates a c++
# header file containing the structure of the data, including functions for reading and writing
# the data.

import gc
import io
import os
import struct
import sys
import time
import polars as pl
import numpy as np
import argparse
import configparser
import glob
from colorama import Fore
import psutil
from pandas.api.types import CategoricalDtype


DUMP_INTERMEDIATES = False

# note: missing category indexes are written as -1
# we could extract these from the dataset, but then they will not be in a suitable order, even with
# sorting so we predefine and check for values in the data that are not listed here
categ_types = {
    "hh_type": CategoricalDtype(categories=["hh", "gq"]),
    "hh_living_arrangement": CategoricalDtype(
        categories=["married", "male_no_spouse", "female_no_spouse", "alone", "not_alone"]
    ),
    "hh_has_kids": CategoricalDtype(categories=["no", "yes"]),
    "hh_dwg": CategoricalDtype(
        # fmt: off
        categories=[
            "single_fam_detach", "single_fam_attach", "2_unit", "3_4_unit", "5_9_unit",
            "10_19_unit", "20_49_unit", "GE50_unit", "mob_home", "other",
        ]
        # fmt: on
    ),
    "hh_tenure": CategoricalDtype(categories=["own", "rent", "other"]),
    "hh_vehicles": CategoricalDtype(categories=["01", "02", "03", "04", "05", "GE06"]),
    "pr_sex": CategoricalDtype(categories=["female", "male"]),
    "pr_race": CategoricalDtype(
        categories=["white", "blk_af_amer", "asian", "native_amer", "pac_island", "other", "mult"]
    ),
    "pr_hsplat": CategoricalDtype(categories=["no", "yes"]),
    "pr_ipr": CategoricalDtype(
        categories=["L050", "050_099", "100_124", "125_149", "150_184", "185_199", "GE200"]
    ),
    "pr_emp_stat": CategoricalDtype(categories=["not.in.force", "unemp", "employed", "mil"]),
    "pr_travel": CategoricalDtype(
        # fmt: off
        categories=[
            "car_truck_van", "public_transportation", "bicycle", "walked", "motorcycle", "taxicab",
            "other", "wfh",
        ]
        # fmt: on
    ),
    "pr_veh_occ": CategoricalDtype(categories=["drove_alone", "carpooled"]),
    "pr_grade": CategoricalDtype(
        # fmt: off
        categories=[
            "childcare", "preschl", "kind", "1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th",
            "9th", "10th", "11th", "12th", "undergrad", "grad",
        ]
        # fmt: on
    ),
    "role": CategoricalDtype(categories=["nope", "worker", "student"]),
    "pr_naics": CategoricalDtype(
        # fmt: off
        categories=[
            "111", "112", "113", "1133", "114", "115", "211", "2121", "2122", "2123", "213",
            "22", "221", "2211", "2212", "2213", "22132", "23", "3", "31", "311", "3113",
            "3114", "3115", "3116", "3118", "311811", "3121", "3122", "3131", "3132", "3133",
            "314", "31411", "315", "316", "3162", "3211", "3212", "3219", "32199", "3221",
            "3222", "32221", "3231", "3241", "32411", "325", "3252", "3253", "3254", "3255",
            "3256", "3261", "3262", "32621", "327", "32711", "327120", "3272", "3279", "33",
            "331", "3313", "3314", "3315", "332", "3321", "3322", "3327", "3328", "33299",
            "333", "3331", "33311", "3333", "3335", "3336", "334", "3341", "3345", "335",
            "3352", "336", "33641", "3365", "3366", "3369", "337", "3391", "3399", "4", "42",
            "4231", "4232", "4233", "4234", "4235", "4236", "4237", "4238", "4239", "42393",
            "424", "4241", "4243", "4244", "4245", "4247", "4248", "4249", "42491", "4251",
            "4411", "4412", "4413", "442", "443141", "443142", "4441", "44413", "4442",
            "44511", "44512", "4452", "4453", "446", "44611", "447", "4481", "44821", "4483",
            "4511", "45113", "45114", "45121", "45221", "4523", "4531", "45321", "45322",
            "4533", "4539", "454110", "4542", "454310", "45439", "481", "482", "483", "484",
            "485", "4853", "486", "487", "488", "491", "492", "493", "5111", "51111", "5112",
            "5121", "5122", "515", "517", "517311", "5182", "5191", "51912", "51913", "52",
            "522", "5221", "5241", "5242", "53", "531", "5313", "532", "5321", "5411", "5412",
            "5413", "5414", "5415", "5416", "5417", "5418", "5419", "54194", "55", "561",
            "5613", "5614", "5615", "5616", "5617", "56173", "562", "611", "6111", "621",
            "6211", "6212", "6213", "62131", "62132", "6214", "6216", "622", "6222", "623",
            "6231", "6241", "6242", "6243", "6244", "711", "7111", "7112", "7115", "712",
            "713", "71395", "721", "7211", "722", "7224", "8111", "811192", "8112", "8113",
            "8114", "8121", "812111", "812112", "8122", "8123", "8129", "813", "8131", "8139",
            "81393", "814", "92", "9211", "92113", "92119", "923", "928"
        ]
        # fmt: on
    ),
}

CORR_CHECK_LEVEL = 0.8

region_scales = {
    12: "blockgroup",
    11: "tract",
    10: "county_subdiv",
    7: "census_places",
    5: "county",
    2: "state",
}

age_levels = {
    "C": [3, 3],
    "P": [4, 4],
    "E": [5, 10],
    "M": [11, 13],
    "H": [14, 17],
    "U": [18, 19],
    "PE": [4, 10],
    "PEM": [4, 13],
    "PEMH": [4, 17],
    "EM": [5, 13],
    "EMH": [5, 17],
    "MH": [11, 17],
}

# these are teacher ratios used to add teachers to the UrbanPop day/night data, *not* for the
# generated data
teacher_ratios = {
    "C": 6.8,
    "P": 12.8,
    "E": 12.8,
    "M": 14.0,
    "H": 15.0,
    "U": 5.5,
    "PE": 12.8,
    "PEM": 13.5,
    "PEMH": 14.2,
    "EM": 13.5,
    "EMH": 14.2,
    "MH": 14.5,
}


def timer(func):
    # @functools.wraps(func)
    def wrapper_timer(*args, **kwargs):
        process = psutil.Process(os.getpid())
        mem_before = process.memory_info().rss
        tic = time.perf_counter()
        value = func(*args, **kwargs)
        toc = time.perf_counter()
        elapsed_time = toc - tic
        mem_after = process.memory_info().rss
        mem_used = float(mem_after - mem_before) / 1024 / 1024 / 1024
        print(
            f"{Fore.BLUE}Elapsed time for {func.__name__}: {elapsed_time:0.2f} seconds, memory {mem_used:0.2f} G{Fore.RESET}"
        )
        return value

    return wrapper_timer


def warn(fmt_str, *args):
    print(f"{Fore.RED}WARNING: {fmt_str}{Fore.RESET}" % args)


def printgreen(fmt_str, *args):
    print(f"{Fore.GREEN}{fmt_str}{Fore.RESET}" % args)


def raise_err(fmt_str, *args):
    raise RuntimeError(f"{Fore.RED}{fmt_str}{Fore.RESET}" % args)


def get_args():
    """Process command line arguments and configuration file settings.

    This function implements a two-stage argument parsing system that allows arguments
    to be specified either via command line or through a configuration file. The process works as
    follows:
    Arguments can be provided in two ways:
    1. Command line: python script.py --output out.csv --upop_files data/*.feather
    2. Config file:  python script.py -c config.cfg
       Where config.cfg contains:
       [main]
       output = out.csv
       upop_files = data/*.feather

    Returns:
        argparse.Namespace: Parsed arguments with all values resolved
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", "-o", help="Output file")
    parser.add_argument(
        "--upop_files", "-f", nargs="+", required=True, help="UrbanPop feather files"
    )
    parser.add_argument(
        "--lodes_files",
        "-l",
        nargs="+",
        required=True,
        default=[],
        help="LODES7 origin-destination (OD) files in CSV format",
    )
    parser.add_argument(
        "--schools_file",
        "-s",
        required=True,
        default="",
        help="File containing schools data in CSV format",
    )
    parser.add_argument("--rseed", "-r", default=29, type=int, help="Random seed")

    main_args = {}
    reqd_args = []
    file_lists = []
    for action in parser._actions:
        main_args[action.dest] = action.default
        if action.required:
            reqd_args.append(action.dest)
        if action.nargs == "+":
            file_lists.append(action.dest)

    cfg_parser = argparse.ArgumentParser(
        description="Convert UrbanPop feather files to a csv file for ExaEpi input", add_help=False
    )
    cfg_parser.add_argument("-c", "--config", help="Config file", metavar="FILE")
    args, remaining_argv = cfg_parser.parse_known_args()
    if args.config:
        cfg = configparser.ConfigParser()
        cfg.read([args.config])
        for item in cfg.items("main"):
            if item[0] not in main_args:
                warn(f"{item[0]} not recognized as a valid argument, ignoring it")
        main_args.update(dict(cfg.items("main")))
        for arg in main_args:
            if arg in reqd_args and (main_args[arg] == "" or main_args[arg] == []):
                raise ValueError(
                    f"Required argument {arg} not specified in config file {args.config}"
                )
            if arg in file_lists and main_args[arg] != []:
                main_args[arg] = glob.glob(main_args[arg])

    new_parser = argparse.ArgumentParser(parents=[cfg_parser])
    for action in parser._actions:
        if action.option_strings[0] == "-h":
            continue
        # Only pass non-None strings to add_argument
        add_arg_kwargs = {
            "dest": action.dest,
            "default": main_args[action.dest],
            "nargs": action.nargs,
            "help": action.help,
            "required": (
                True
                if action.required
                and (
                    main_args[action.dest] == ""
                    or main_args[action.dest] == []
                    or main_args[action.dest] is None
                )
                else False
            ),
        }
        if action.type is not None:
            add_arg_kwargs["type"] = action.type
        new_parser.add_argument(
            *[opt for opt in action.option_strings if opt is not None],
            **add_arg_kwargs,
        )
    args = new_parser.parse_args(remaining_argv)
    print(Fore.CYAN, "Options:", sep="")
    for arg, value in args.__dict__.items():
        print(f"  {arg:20s} {value}")
    print(Fore.RESET, end="")
    return args


def dump_intermediate(df: pl.DataFrame, fname: str, override: bool = False):
    if DUMP_INTERMEDIATES or override:
        print(f"{Fore.CYAN}Dumping intermediate file {fname}.intermediate.csv{Fore.RESET}")
        # Replace empty strings with null before writing
        str_cols = [col for col, dtype in df.schema.items() if dtype == pl.Utf8]
        if str_cols:
            df = df.with_columns(
                [
                    pl.when(pl.col(col) == "").then(None).otherwise(pl.col(col)).alias(col)
                    for col in str_cols
                ]
            )
        df.write_csv(fname + ".intermediate.csv", quote_style="necessary")


@timer
def load_upop_feather_files(fnames: list[str], out_fname: str = "") -> pl.DataFrame:
    printgreen(f"Reading UrbanPop data from {len(fnames)} files")
    dfs = []
    df = pl.DataFrame()
    chunk_size = int(len(fnames) / 10)
    for i, fname in enumerate(fnames):
        df_read = pl.read_ipc(fname, memory_map=False)
        dfs.append(df_read)
        # Concatenate and clean up at chunk boundaries or end
        if i == len(fnames) - 1 or (chunk_size > 0 and (i + 1) % chunk_size == 0):
            df = pl.concat(dfs)
            dfs = [df]  # Keep only the concatenated result
            gc.collect()

            mem_used = float(psutil.Process(os.getpid()).memory_info().rss) / 1024 / 1024 / 1024
            mem_of_df = float(df.estimated_size()) / 1024 / 1024 / 1024  # polars method

            if chunk_size > 0:
                print(f"  {int((i + 1) / chunk_size)}:", end="")
            print(f" read {fname}, memory RSS {mem_used:0.2f} G, memory of df {mem_of_df:0.2f} G")

    df = dfs[0]
    print(f"Read {len(df)} records")

    # need to sort to ensure the order is the same between the population files and the
    # daytime/nighttime files
    df.sort("p_id")
    if out_fname != "":
        dump_intermediate(df, out_fname + ".upop")
    return df


@timer
def set_types(df: pl.DataFrame) -> pl.DataFrame:
    printgreen("Setting types")
    # Extract NAICS digits and convert h_id in one pass
    df = df.with_columns(
        [
            pl.col("pr_naics").str.extract(r"(\d+)", 0).fill_null("-1").alias("pr_naics"),
            pl.col("h_id")
            .str.split("-")
            .list.last()
            .cast(pl.Int32, strict=False)
            .fill_null(-1)
            .alias("h_id"),
        ]
    )
    # Build categorical mappings once
    categorical_mappings = {}
    for field_type, categ_dtype in categ_types.items():
        if field_type not in df.columns or field_type == "pr_naics":
            continue
        categs_expected = list(categ_dtype.categories)
        # Check for missing categories
        categs_found = df[field_type].unique().drop_nulls().to_list()
        missing = [x for x in categs_found if x not in categs_expected and x != "" and x != "-1"]
        if missing:
            warn(f"Found missing categories for {field_type}: {missing}")
        # Create categorical mapping
        cat_mapping = {cat: idx for idx, cat in enumerate(categs_expected)}
        cat_mapping[""] = -1
        # Determine appropriate dtype based on number of categories
        num_categories = len(categs_expected)
        if num_categories < 127:
            return_dtype = pl.Int8
        elif num_categories < 32767:
            return_dtype = pl.Int16
        else:
            return_dtype = pl.Int32
        categorical_mappings[field_type] = (cat_mapping, return_dtype)
    # Apply all categorical mappings in one operation
    if categorical_mappings:
        df = df.with_columns(
            [
                pl.col(field_type)
                .fill_null("")
                .replace_strict(cat_mapping, default=-1)
                .cast(return_dtype)
                .alias(field_type)
                for field_type, (cat_mapping, return_dtype) in categorical_mappings.items()
            ]
        )
    # Optimize integer types for non-categorical columns in batch
    cols_to_optimize = [
        col for col in df.columns if col not in categ_types and col not in ["pr_naics", "h_id"]
    ]
    # Collect all type changes first
    type_changes = []
    for col in cols_to_optimize:
        dtype = df[col].dtype
        if dtype not in [pl.Int64, pl.Int32, pl.Int16, pl.Int8, pl.Float32, pl.Float64]:
            continue
        max_val = df[col].max()
        if max_val is None or not isinstance(max_val, (int, float)):
            continue
        # Determine optimal type
        if max_val < 128:
            new_dtype = pl.Int8
        elif max_val < 2**15:
            new_dtype = pl.Int16
        elif max_val < 2**31:
            new_dtype = pl.Int32
        else:
            new_dtype = pl.Int64
        if new_dtype != dtype:
            type_changes.append(pl.col(col).cast(new_dtype))
    # Apply all type changes in one operation
    if type_changes:
        df = df.with_columns(type_changes)
    # Handle pr_naics separately (still a string at this point)
    if "pr_naics" in categ_types and "pr_naics" in df.columns:
        naics_categs = list(categ_types["pr_naics"].categories)
        naics_mapping = {cat: idx for idx, cat in enumerate(naics_categs)}
        naics_mapping["-1"] = -1
        naics_mapping[""] = -1
        # Use replace instead of map_elements for better performance
        # For values not in mapping, try to cast to int
        df = df.with_columns(
            [
                pl.col("pr_naics")
                .replace_strict(naics_mapping, default=None)
                .fill_null(
                    # Try to convert remaining values to int
                    pl.col("pr_naics")
                    .cast(pl.Int16, strict=False)
                    .fill_null(-1)
                )
                .cast(pl.Int16)
                .alias("pr_naics")
            ]
        )
    return df


def rename_fields(df: pl.DataFrame) -> pl.DataFrame:
    # Rename base fields
    df = df.rename({"geoid": "home_geoid", "h_id": "household_id", "p_id": "id"})
    # Build a mapping dictionary for all column renames
    rename_map = {}
    for col in df.columns:
        if col.startswith("pr_"):
            rename_map[col] = col[3:]
        elif col.startswith("h_"):
            rename_map[col] = "home_" + col[2:]
        elif col.startswith("w_"):
            rename_map[col] = "work_" + col[2:]
        elif col.startswith("hh_"):
            rename_map[col] = "household_" + col[3:]
    # Apply all renames at once
    if rename_map:
        df = df.rename(rename_map)
    return df


def get_school_level_from_age(start_age: int, end_age: int) -> str:
    PREK_SCHOOL_AGES = [0, 4]
    ELEM_SCHOOL_AGES = [5, 10]
    MID_SCHOOL_AGES = [11, 13]
    HIGH_SCHOOL_AGES = [14, 18]
    LEVEL_KEYS = {0: "P", 1: "E", 2: "M", 3: "H"}

    levels = ""
    try:
        start_age = int(start_age)
        end_age = int(end_age)
    except:
        # if the age ranges are messed up, just use full range
        start_age = ELEM_SCHOOL_AGES[0]
        end_age = HIGH_SCHOOL_AGES[1]
    for i, (low_age, high_age) in enumerate(
        [PREK_SCHOOL_AGES, ELEM_SCHOOL_AGES, MID_SCHOOL_AGES, HIGH_SCHOOL_AGES]
    ):
        if start_age >= low_age and start_age <= high_age:
            levels += LEVEL_KEYS[i]
        elif end_age >= low_age and end_age <= high_age:
            levels += LEVEL_KEYS[i]
        elif start_age < low_age and end_age > high_age:
            levels += LEVEL_KEYS[i]
    # for those rare cases when no start and end grades are present, just assume the schools handles all levels
    if levels == "":
        levels = "PEMH"
    return levels


def get_level_from_age(min_age: int, max_age: int):
    if min_age >= 18:
        return "U"
    if max_age == 3:
        return "C"
    return get_school_level_from_age(min_age, max_age)


@timer
def process_upop(df: pl.DataFrame, out_fname: str) -> pl.DataFrame:
    printgreen("Processing UrbanPop data")
    # only include these fields in the output csv and c++ structure
    include_fields = {
        "p_id",
        # "pums_id",
        "h_id",
        "geoid",
        # "hh_size",
        # "hh_type",
        # "hh_living_arrangement",
        # "hh_age",
        # "hh_has_kids",
        # "hh_income",
        # "hh_nb_wrks",
        # "hh_nb_non_wrks",
        # "hh_nb_adult_wrks",
        # "hh_nb_adult_non_wrks",
        # "hh_dwg",
        # "hh_tenure",
        # "hh_vehicles",
        "pr_age",
        "pr_sex",
        "pr_race",
        # "pr_hsplat",
        # "pr_ipr",
        "pr_naics",
        # "pr_emp_stat",
        "pr_travel",
        "pr_veh_occ",
        # "pr_commute",
        "pr_grade",
    }
    # Drop columns not in include_fields
    cols_to_keep = [col for col in df.columns if col in include_fields]
    df = df.select(cols_to_keep)
    df = set_types(df)
    df = rename_fields(df)
    # Add 3 to grade for students (grade != -1)
    df = df.with_columns(
        [
            pl.when(pl.col("grade") != -1)
            .then(pl.col("grade") + 3)
            .otherwise(pl.col("grade"))
            .alias("grade")
        ]
    )
    dump_intermediate(df, out_fname + ".upop.purged")
    return df


@timer
def get_lodes_groups(lodes_fnames: list[str]) -> pl.DataFrame:
    printgreen("Loading LODES files")
    # Origin-Destination (OD) File Structure (LODES flows)
    # Pos Variable Type Explanation
    # 1 w_geocode Char15 Workplace Census Block Code
    # 2 h_geocode Char15 Residence Census Block Code
    # 3 S000 Num Total number of jobs
    # 4 SA01 Num Number of jobs of workers age 29 or younger
    # 5 SA02 Num Number of jobs for workers age 30 to 54
    # 6 SA03 Num Number of jobs for workers age 55 or older
    # 7 SE01 Num Number of jobs with earnings $1250/month or less
    # 8 SE02 Num Number of jobs with earnings $1251/month to $3333/month
    # 9 SE03 Num Number of jobs with earnings greater than $3333/month
    # 10 SI01 Num Number of jobs in Goods Producing industry sectors
    # 11 SI02 Num Number of jobs in Trade, Transportation, and Utilities industry sectors
    # 12 SI03 Num Number of jobs in All Other Services industry sectors
    # 13 createdate Char Date on which data was created, formatted as YYYYMMDD
    dfs = []
    for lodes_fname in lodes_fnames:
        print("Loading", lodes_fname)
        lodes_df = pl.read_csv(lodes_fname, columns=["w_geocode", "h_geocode", "S000"])
        lodes_df = lodes_df.with_columns(
            [
                pl.col("w_geocode").cast(pl.Utf8),
                pl.col("h_geocode").cast(pl.Utf8),
                pl.col("S000").cast(pl.Int32),
            ]
        )
        # truncate geoids to first 12, i.e. just census block groups
        lodes_df = lodes_df.with_columns(
            [pl.col("h_geocode").str.slice(0, 12), pl.col("w_geocode").str.slice(0, 12)]
        )

        lodes_df = lodes_df.group_by(["w_geocode", "h_geocode"], maintain_order=True).agg(
            pl.col("S000").sum().alias("count")
        )
        dump_intermediate(lodes_df, lodes_fname + "_short")
        dfs.append(lodes_df)
    df = pl.concat(dfs)
    return df


@timer
def set_childcare(upop_df: pl.DataFrame) -> pl.DataFrame:
    printgreen("Setting childcare")
    # UrbanPop doesn't have allocations to childcare outside of PK in schools, so we randomly
    # assign agents under age 5 not in PK to childcare. According to NCES, 32% of under 1 year,
    # 47% of 1-2 yrs and 83 of 3-5 yrs are in center-based care
    PROBS = {0: 0.32, 1: 0.47, 2: 0.47, 3: 0.83, 4: 0.83}
    # Create a list to collect row indices to update
    indices_to_update = []
    for age in range(0, 5):
        # Filter candidates for this age
        candidates = upop_df.filter((pl.col("grade") == -1) & (pl.col("age") == age))
        num_candidates = int(len(candidates) * PROBS[age])
        if num_candidates > 0:
            # Sample random candidates - uses np random seed
            sampled = candidates.sample(n=num_candidates, shuffle=True, seed=None)
            indices_to_update.extend(sampled["id"].to_list())
            print(f"  Age {age} set {len(sampled)} out of {len(candidates)}")
    # Update grades for selected agents
    upop_df = upop_df.with_columns(
        [
            pl.when(pl.col("id").is_in(indices_to_update))
            .then(pl.lit(3, dtype=pl.Int8))
            .otherwise(pl.col("grade"))
            .alias("grade")
        ]
    )
    print(f"Set {len(upop_df.filter(pl.col('grade') == 3))} agents to childcare")
    dump_intermediate(upop_df, "childcare")
    return upop_df


@timer
def load_schools(fname: str) -> pl.DataFrame:
    printgreen(f"Loading schools from {fname}")
    schools_df = pl.read_csv(fname, schema_overrides={"geoid": pl.Utf8, "id": pl.Utf8})
    print(
        f"Loaded {len(schools_df)} entries: {schools_df["students"].sum()} students, "
        f"{schools_df["teachers"].sum()} teachers"
    )
    dump_intermediate(schools_df, "schools")
    return schools_df


@timer
def alloc_workers(lodes_df: pl.DataFrame, workers_df: pl.DataFrame) -> pl.DataFrame:
    printgreen("Allocating workers")
    # Get unique worker home geoids
    worker_geoids = set(workers_df["home_geoid"].unique().to_list())
    # Filter LODES data to only include flows between worker geoids
    lodes_df = lodes_df.filter(
        pl.col("w_geocode").is_in(worker_geoids) & pl.col("h_geocode").is_in(worker_geoids)
    )
    # Group by home geoid and LODES origin
    worker_groups = workers_df.group_by("home_geoid", maintain_order=True)
    lodes_groups_dict = {
        name: group for name, group in lodes_df.group_by("h_geocode", maintain_order=True)
    }
    num_geoids = workers_df["home_geoid"].n_unique()
    print(f"Assigning workers in {num_geoids} GEOIDS for {len(lodes_groups_dict)} LODES groups")

    all_workers = []
    i = 0
    for home_geoid, worker_group in worker_groups:
        i += 1
        if i % 100 == 0:
            print(f"  {i} {home_geoid[0]}")
        num_workers = len(worker_group)
        # Try to get matching LODES group
        lodes_group = lodes_groups_dict.get(home_geoid)
        if lodes_group is None:
            # the home geoid derived from the upop workers is not found in the home (origin) geoid
            # in the LODES data, so we have no flows from that geoid
            warn(
                f"Could not find origin GEOID {home_geoid} in LODES data for {num_workers} workers"
            )
            lodes_group = pl.DataFrame(
                {"w_geocode": [home_geoid], "h_geocode": [home_geoid], "count": [num_workers]}
            )
        sum_flows = lodes_group["count"].sum()
        flow_probs = (lodes_group["count"] / sum_flows).to_numpy()
        # Sample work locations based on flow probabilities
        work_geocodes = lodes_group["w_geocode"].to_list()
        sampled_work = np.random.choice(work_geocodes, size=num_workers, p=flow_probs)
        # Add work_geoid to workers
        worker_ids = worker_group["id"].to_list()
        for worker_id, work_geoid in zip(worker_ids, sampled_work):
            all_workers.append({"id": worker_id, "work_geoid": work_geoid})

    work_assignments = pl.DataFrame(all_workers)
    # Join with original workers
    workers_df = workers_df.join(work_assignments, on="id", how="left")
    # Set grade to -1 and school_id to empty for all workers
    workers_df = workers_df.with_columns(
        [pl.lit(-1, dtype=pl.Int8).alias("grade"), pl.lit("").alias("school_id")]
    )
    # Check for workers without NAICS
    num_without_naics = len(workers_df.filter(pl.col("naics") == -1))
    if num_without_naics > 0:
        warn(f"There are {num_without_naics} workers without NAICS classification")
    print("Added destinations for", len(workers_df), "workers")
    dump_intermediate(workers_df, "workers_nt_dt")

    return workers_df


def process_students_region(
    region: str,
    student_group: pl.DataFrame,
    school_groups_dict: dict[str, pl.DataFrame],
    alloc_all: bool,
) -> tuple[list[str], list[str], list[str], pl.DataFrame] | None:
    num_students_reqd = len(student_group)
    if num_students_reqd == 0:
        warn(f"No students requested for group {region}")
        return None
    # Try to get matching school group
    school_group = school_groups_dict.get(region)
    if school_group is None:
        # No schools in this region
        return None
    # Select only needed columns
    school_group = school_group.select(["geoid", "id", "remaining_student_places"])
    sum_remaining_student_places = school_group["remaining_student_places"].sum()
    if not alloc_all and num_students_reqd > sum_remaining_student_places:
        # Add extra dummy row so all students have chance of being allocated
        dummy_row = pl.DataFrame(
            {
                "geoid": [""],
                "id": [""],
                "remaining_student_places": [num_students_reqd - sum_remaining_student_places],
            },
            schema={
                "geoid": pl.Utf8,
                "id": pl.Utf8,
                "remaining_student_places": school_group["remaining_student_places"].dtype,
            },
        )
        school_group = pl.concat([school_group, dummy_row])
        sum_remaining_student_places = school_group["remaining_student_places"].sum()
    # Sample schools based on probabilities
    # Calculate probabilities for weighted sampling
    school_probs = (
        school_group["remaining_student_places"] / sum_remaining_student_places
    ).to_numpy()
    # Use numpy random choice with weights, then select those rows
    school_rnd_indices = np.random.choice(
        len(school_group), size=num_students_reqd, replace=True, p=school_probs
    )
    # Select schools by indices
    schools_selected = school_group[school_rnd_indices]
    geoids = schools_selected["geoid"].to_list()
    school_ids = schools_selected["id"].to_list()
    # Filter out dummy schools
    schools_selected = schools_selected.filter(pl.col("id") != "")
    if len(schools_selected) == 0:
        return None
    # Count assignments per school
    counts = schools_selected.group_by("id", maintain_order=True).agg(pl.len().alias("count"))
    return student_group["id"].to_list(), geoids, school_ids, counts


def alloc_students_region(
    level: str,
    students_df: pl.DataFrame,
    schools_df: pl.DataFrame,
    geoid_scaling: int,
    alloc_all: bool,
) -> tuple[pl.DataFrame, pl.DataFrame]:
    # Add region column based on geoid scaling
    schools_df = schools_df.with_columns(
        [pl.col("geoid").str.slice(0, geoid_scaling).alias("region")]
    )
    # dump_intermediate(schools_df, "schools_" + region_scales[geoid_scaling] + "-" + level)
    students_df = students_df.with_columns(
        [pl.col("home_geoid").str.slice(0, geoid_scaling).alias("region")]
    )
    # dump_intermediate(students_df, "students_" + region_scales[geoid_scaling] + "-" + level)
    # Group by region
    student_groups_dict = {}
    for key_tuple, group_df in students_df.group_by("region", maintain_order=True):
        # Extract the string value from the tuple
        region = key_tuple[0] if isinstance(key_tuple, tuple) else key_tuple
        student_groups_dict[region] = group_df
    school_groups_dict = {}
    for key_tuple, group_df in schools_df.group_by("region", maintain_order=True):
        region = key_tuple[0] if isinstance(key_tuple, tuple) else key_tuple
        school_groups_dict[region] = group_df
    all_student_ids = []
    all_work_geoids = []
    all_school_ids = []
    all_school_counts = []
    # Process all regions
    for region, group in student_groups_dict.items():
        result = process_students_region(region, group, school_groups_dict, alloc_all)
        if result is None:
            continue
        all_student_ids.extend(result[0])
        all_work_geoids.extend(result[1])
        all_school_ids.extend(result[2])
        all_school_counts.append(result[3])
    if len(all_student_ids) > 0:
        updates_df = pl.DataFrame(
            {
                "id": all_student_ids,
                "work_geoid": all_work_geoids,
                "school_id": all_school_ids,
            }
        )
        school_counts_df = pl.concat(all_school_counts)
        # Update students dataframe
        students_df = students_df.join(updates_df, on="id", how="left", suffix="_new")
        students_df = students_df.with_columns(
            [
                pl.when(pl.col("work_geoid_new").is_not_null())
                .then(pl.col("work_geoid_new"))
                .otherwise(pl.col("work_geoid"))
                .alias("work_geoid"),
                pl.when(pl.col("school_id_new").is_not_null())
                .then(pl.col("school_id_new"))
                .otherwise(pl.col("school_id"))
                .alias("school_id"),
            ]
        ).drop(["work_geoid_new", "school_id_new"])
        # Update schools dataframe
        # Aggregate all school counts by id
        school_counts_agg = school_counts_df.group_by("id", maintain_order=True).agg(
            pl.col("count").sum().alias("allocated_count")
        )
        schools_df = schools_df.join(school_counts_agg, on="id", how="left")
        schools_df = schools_df.with_columns(
            [
                pl.when(pl.col("allocated_count").is_not_null())
                .then(pl.col("remaining_student_places") - pl.col("allocated_count"))
                .otherwise(pl.col("remaining_student_places"))
                .alias("remaining_student_places")
            ]
        ).drop("allocated_count")
        # Clip to minimum of 1
        schools_df = schools_df.with_columns(
            [pl.col("remaining_student_places").clip(lower_bound=1)]
        )
    num_allocated = len(students_df.filter(pl.col("school_id") != ""))
    print(
        f"  For {region_scales[geoid_scaling]}, allocated {num_allocated} students "
        f"out of {len(students_df)}"
    )
    # Drop region column
    students_df = students_df.drop("region")
    schools_df = schools_df.drop("region")
    return students_df, schools_df


@timer
def alloc_students_level(
    schools_df: pl.DataFrame, students_df: pl.DataFrame, level: str
) -> pl.DataFrame:
    ids_before = students_df["id"].to_list()
    print(f"Allocating {len(students_df)} students for level {level}")
    dump_intermediate(students_df.select(["id", "grade"]), "students-" + level)
    # Get all schools with the required level
    schools_df = schools_df.filter(pl.col("level").str.contains(level))
    # Some schools have multiple levels and so students should be allocated proportionately. For
    # simplicity, we just allocate uniformly among the levels, e.g. a EMH school would have 1/3
    # students each in elem, middle and high
    schools_df = schools_df.with_columns(
        [
            (pl.col("students") / pl.col("level").str.len_chars())
            .ceil()
            .cast(pl.Int32)
            .alias("students")
        ]
    )
    schools_df = schools_df.with_columns([pl.col("students").alias("remaining_student_places")])
    # for childcare, we assume that it is all close to home
    scales = list(region_scales.keys()) if level != "C" else list(region_scales.keys())[:3]
    # pick schools for students from decreasing resolution; the goal is to allocate students as
    # close to home as possible
    for scale in scales:
        # make sure to allocate all at the final region scale
        alloc_all = True if scale == scales[-1] else False
        unassigned_df = students_df.filter(pl.col("school_id") == "")
        assigned_df, schools_df = alloc_students_region(
            level, unassigned_df, schools_df, scale, alloc_all
        )
        # Update students_df with assignments
        if len(assigned_df) > 0:
            # Create update dataframe with only assigned students
            update_df = assigned_df.select(["id", "school_id", "work_geoid"])
            # Join and update
            students_df = students_df.join(update_df, on="id", how="left", suffix="_new")
            students_df = students_df.with_columns(
                [
                    pl.when(pl.col("school_id_new").is_not_null())
                    .then(pl.col("school_id_new"))
                    .otherwise(pl.col("school_id"))
                    .alias("school_id"),
                    pl.when(pl.col("work_geoid_new").is_not_null())
                    .then(pl.col("work_geoid_new"))
                    .otherwise(pl.col("work_geoid"))
                    .alias("work_geoid"),
                ]
            ).drop(["school_id_new", "work_geoid_new"])
        num_unalloc = len(students_df.filter(pl.col("school_id") == ""))
        if num_unalloc == 0:
            break
    num_unalloc = len(students_df.filter(pl.col("school_id") == ""))
    if num_unalloc > 0:
        students_df = students_df.with_columns(
            [
                pl.when(pl.col("school_id") == "")
                .then(pl.col("home_geoid"))
                .otherwise(pl.col("work_geoid"))
                .alias("work_geoid"),
                pl.when(pl.col("school_id") == "")
                .then(pl.lit(-1, dtype=pl.Int8))
                .otherwise(pl.col("grade"))
                .alias("grade"),
            ]
        )
    ids_after = students_df["id"].to_list()
    if ids_before != ids_after:
        raise_err(f"mismatched ids: {len(ids_before)} != {len(ids_after)}")
    return students_df


@timer
def alloc_students(schools_df: pl.DataFrame, students_df: pl.DataFrame) -> pl.DataFrame:
    printgreen("Allocating students")
    num_unique_before = students_df["id"].n_unique()
    # Add initial columns
    students_df = students_df.with_columns(
        [
            pl.lit("").alias("school_id"),
            pl.lit(-1, dtype=pl.Int16).alias("naics"),
            pl.col("home_geoid").alias("work_geoid"),
        ]
    )
    dfs = []
    # allocate students from each level
    for level in ["P", "E", "M", "H", "U", "C"]:
        level_students_df = students_df.filter(
            (pl.col("grade") >= age_levels[level][0]) & (pl.col("grade") <= age_levels[level][1])
        )
        if len(level_students_df) == 0:
            continue
        level_students_df = alloc_students_level(schools_df, level_students_df, level=level)
        dfs.append(level_students_df)
    students_df = pl.concat(dfs)
    num_unique_after = students_df["id"].n_unique()
    if num_unique_before != num_unique_after:
        warn(f"mismatched unique ids: {num_unique_before} != {num_unique_after}")
    # set all unallocated students
    unalloc_count = len(students_df.filter(pl.col("school_id") == ""))
    if unalloc_count > 0:
        warn(f"Found {unalloc_count} unallocated students")
        students_df = students_df.with_columns(
            [
                pl.when(pl.col("school_id") == "")
                .then(pl.col("home_geoid"))
                .otherwise(pl.col("work_geoid"))
                .alias("work_geoid"),
                pl.when(pl.col("school_id") == "")
                .then(pl.lit(-1, dtype=pl.Int8))
                .otherwise(pl.col("grade"))
                .alias("grade"),
            ]
        )
    dump_intermediate(students_df, "students_nt_dt")
    return students_df


def check_school_id_correlation(
    students_df: pl.DataFrame, schools_df: pl.DataFrame, description: str
):
    # now check correlation of generated data with actual schools data, for each named school size
    gen_schools_df = students_df.group_by("school_id", maintain_order=True).agg(
        pl.len().alias("students")
    )
    gen_schools_df = gen_schools_df.with_columns([pl.col("school_id").cast(pl.Utf8).alias("key")])
    schools_check_df = schools_df.with_columns([pl.col("id").cast(pl.Utf8).alias("key")])
    # only merge in the matching schools from the actual data, since that consists of potentially
    # many more schools than we are using for this subset (e.g. if we are doing a single state)
    merged_df = gen_schools_df.join(
        schools_check_df.select(["key", "students"]), on="key", how="left", suffix="_orig"
    ).select(["key", "students", "students_orig"])
    merged_df = merged_df.with_columns(
        [
            pl.col("students_orig").fill_null(0).cast(pl.Int32),
            pl.col("students").cast(pl.Int32).alias("students_gen"),
        ]
    ).select(["key", "students_gen", "students_orig"])
    dump_intermediate(merged_df, "schools_check_name")
    corr = merged_df.select(pl.corr("students_gen", "students_orig")).item()
    print(
        f"{description} school ID correlation: {corr:.3f} "
        + f"(generated count {merged_df['students_gen'].sum()}, "
        f"actual count {merged_df['students_orig'].sum()})"
    )
    if corr < CORR_CHECK_LEVEL:
        warn("Low correlation!")


def check_school_geoid_correlation(
    students_df: pl.DataFrame, schools_df: pl.DataFrame, description: str
):
    # now check correlation for location (geoid)
    gen_schools_df = students_df.group_by(["work_geoid"], maintain_order=True).agg(
        pl.len().alias("count")
    )
    gen_schools_df = gen_schools_df.with_columns([pl.col("work_geoid").cast(pl.Utf8).alias("key")])
    schools_check_df = schools_df.group_by(["geoid"], maintain_order=True).agg(
        pl.col("students").sum().alias("count")
    )
    schools_check_df = schools_check_df.with_columns([pl.col("geoid").cast(pl.Utf8).alias("key")])
    # only merge in the matching schools from the actual data, since that consists of potentially
    # many more schools than we are using for this subset (e.g. if we are doing a single state)
    merged_df = gen_schools_df.join(
        schools_check_df.select(["key", "count"]), on="key", how="left", suffix="_orig"
    ).select(["key", "count", "count_orig"])
    merged_df = merged_df.with_columns(
        [
            pl.col("count_orig").fill_null(0).cast(pl.Int32),
            pl.col("count").cast(pl.Int32).alias("count_gen"),
        ]
    ).select(["key", "count_gen", "count_orig"])
    dump_intermediate(merged_df, "schools_check_geoid")
    corr = merged_df.select(pl.corr("count_gen", "count_orig")).item()
    print(
        f"{description} school geoid correlation: {corr:.3f} "
        + f"(generated count {merged_df['count_gen'].sum()}, "
        f"actual count {merged_df['count_orig'].sum()})"
    )
    if corr < CORR_CHECK_LEVEL:
        warn("Low correlation!")


def print_school_counts(students_df: pl.DataFrame, workers_df: pl.DataFrame):
    print("School counts (educators, students, ratio):")
    level_names = {
        "C": "Childcare",
        "PE": "Elementary",
        "M": "Middle",
        "H": "High",
        "U": "College",
    }
    tot_students = 0
    tot_teachers = 0
    for level in ["U", "H", "M", "PE", "C"]:
        num_students = len(
            students_df.filter(
                (pl.col("grade") >= age_levels[level][0])
                & (pl.col("grade") <= age_levels[level][1])
            )
        )
        tot_students += num_students
        num_teachers = len(
            workers_df.filter(
                (pl.col("grade") >= age_levels[level][0])
                & (pl.col("grade") <= age_levels[level][1])
            )
        )
        print(
            f"  {level_names[level]:10s} {num_teachers} {num_students} "
            f"{num_students / num_teachers:.1f}"
        )
        tot_teachers += num_teachers
    print(f"  Total     {tot_teachers} {tot_students} {tot_students / tot_teachers:.1f}")


@timer
def generate_nt_dt(
    schools_df: pl.DataFrame, upop_df: pl.DataFrame, lodes_df: pl.DataFrame
) -> tuple[pl.DataFrame, pl.DataFrame, pl.DataFrame, pl.DataFrame]:
    # randomly allocate some young agents to childcare
    upop_df = set_childcare(upop_df)
    num_unique_ids = upop_df["id"].n_unique()
    # now split into students, workers and unemployed.
    # Note that the UrbanPop nt/dt data classifies mil as unemployed (nope); because they don't
    # commute?
    # UrbanPop nt/dt sometimes classifies employed people with assigned grades as students, not
    # workers. Not sure when/why it does this. We will assume that employed agents with assigned
    # grades are students if they are under 25 in age. We determine who is employed by checking who
    # has a NAICS code
    is_employed = (pl.col("naics") != -1) & ((pl.col("grade") == -1) | (pl.col("age") > 26))
    in_school = (pl.col("grade") != -1) & ~is_employed
    students_df = upop_df.filter(in_school)
    workers_df = upop_df.filter(is_employed)
    unemp_df = upop_df.filter(~is_employed & ~in_school)
    tot = len(workers_df) + len(students_df) + len(unemp_df)
    print("Counts:")
    print("  workers:   ", len(workers_df))
    print("  students:  ", len(students_df))
    print("  unemployed:", len(unemp_df))
    print("  total:     ", tot)
    if tot != len(upop_df):
        print(
            "ERROR: total agents mismatch, allocated",
            tot,
            "but found",
            len(upop_df),
            "in UrbanPop feather files",
        )
    unemp_df = unemp_df.with_columns(
        [
            pl.col("home_geoid").alias("work_geoid"),
            pl.lit("").alias("school_id"),
            pl.lit(-1, dtype=pl.Int8).alias("grade"),
            pl.lit(-1, dtype=pl.Int16).alias("naics"),
        ]
    )
    workers_nt_dt_df = alloc_workers(lodes_df, workers_df)
    if num_unique_ids != (len(workers_nt_dt_df) + len(students_df) + len(unemp_df)):
        raise_err(f"Incorrect number of unique IDS after worker allocation")
    students_nt_dt_df = alloc_students(schools_df, students_df)
    if num_unique_ids != (len(workers_nt_dt_df) + len(students_nt_dt_df) + len(unemp_df)):
        print(len(students_df), len(students_nt_dt_df))
        raise_err(f"Incorrect number of unique IDS after student allocation")

    return workers_nt_dt_df, students_nt_dt_df, schools_df, unemp_df


def alloc_teachers_region(
    teachers_df: pl.DataFrame, schools_df: pl.DataFrame, geoid_scaling: int
) -> tuple[pl.DataFrame, pl.DataFrame]:
    schools_df = schools_df.with_columns(
        [pl.col("geoid").str.slice(0, geoid_scaling).alias("region")]
    )
    teachers_df = teachers_df.with_columns(
        [pl.col("work_geoid").str.slice(0, geoid_scaling).alias("region")]
    )
    teacher_groups_dict = {
        name: group for name, group in teachers_df.group_by("region", maintain_order=True)
    }
    school_groups_dict = {
        name: group for name, group in schools_df.group_by("region", maintain_order=True)
    }
    missing_regions = 0
    tot_reqd_teachers = 0
    for group_name, school_group in school_groups_dict.items():
        num_teachers_reqd = int(school_group["adj_teachers"].sum())
        if num_teachers_reqd == 0:
            continue
        tot_reqd_teachers += num_teachers_reqd
        teacher_group = teacher_groups_dict.get(group_name)
        if teacher_group is None:
            missing_regions += 1
            continue
        num_teachers_reqd = min(num_teachers_reqd, len(teacher_group))
        teachers_selected = teacher_group.sample(n=num_teachers_reqd, shuffle=True)
        probs = (school_group["adj_teachers"] / school_group["adj_teachers"].sum()).to_numpy()
        probs = probs / probs.sum()  # Normalize
        school_indices = np.random.choice(
            len(school_group), size=num_teachers_reqd, replace=True, p=probs
        )
        schools_selected = school_group[school_indices]
        # Assign grades based on school level
        levels_array = schools_selected["level"].to_numpy()
        grades = np.zeros(len(levels_array), dtype=np.int8)
        for level, (min_age, max_age) in age_levels.items():
            mask = levels_array == level
            if mask.any():
                grades[mask] = np.random.randint(min_age, max_age + 1, size=mask.sum())
        # Check for unknown levels
        if np.any(grades == 0):
            unknown_levels = np.unique(levels_array[grades == 0])
            raise_err(f"Unknown school levels: {unknown_levels}")
        schools_selected = schools_selected.with_columns(
            [pl.Series("grade", grades, dtype=pl.Int8)]
        )
        # Adjust university teachers: 50% undergrad (18), 50% grad (19) -> change to 80:20
        grades_array = schools_selected["grade"].to_numpy()
        rnd_vals = np.random.uniform(size=len(schools_selected))
        adjusted_grades = np.where((grades_array == 19) & (rnd_vals < 0.5), 18, grades_array)
        schools_selected = schools_selected.with_columns(
            [pl.Series("grade", adjusted_grades, dtype=pl.Int8)]
        )
        # Convert school IDs to string
        schools_selected = schools_selected.with_columns([pl.col("id").cast(pl.Utf8)])
        teacher_ids = teachers_selected["id"].to_list()
        school_ids = schools_selected["id"].to_list()
        work_geoids = schools_selected["geoid"].to_list()
        teacher_grades = schools_selected["grade"].to_list()
        # Apply updates to teachers_df
        updates_df = pl.DataFrame(
            {
                "id": teacher_ids,
                "school_id": school_ids,
                "work_geoid": work_geoids,
                "grade": teacher_grades,
            }
        )
        # Join and update in one operation
        teachers_df = teachers_df.join(updates_df, on="id", how="left", suffix="_new")
        teachers_df = teachers_df.with_columns(
            [
                pl.when(pl.col("school_id_new").is_not_null())
                .then(pl.col("school_id_new"))
                .otherwise(pl.col("school_id"))
                .alias("school_id"),
                pl.when(pl.col("work_geoid_new").is_not_null())
                .then(pl.col("work_geoid_new"))
                .otherwise(pl.col("work_geoid"))
                .alias("work_geoid"),
                pl.when(pl.col("grade_new").is_not_null())
                .then(pl.col("grade_new"))
                .otherwise(pl.col("grade"))
                .alias("grade"),
            ]
        ).drop(["school_id_new", "work_geoid_new", "grade_new"])
        # Count how many teachers were assigned to each school
        school_counts = schools_selected.group_by("id", maintain_order=True).agg(
            pl.len().alias("count")
        )
        # Join counts with schools_df
        schools_df = schools_df.join(school_counts, on="id", how="left")
        schools_df = schools_df.with_columns(
            [
                pl.when(pl.col("count").is_not_null())
                .then(pl.col("adj_teachers") - pl.col("count"))
                .otherwise(pl.col("adj_teachers"))
                .alias("adj_teachers"),
                pl.when(pl.col("count").is_not_null())
                .then(pl.col("alloc_teachers") - pl.col("count"))
                .otherwise(pl.col("alloc_teachers"))
                .alias("alloc_teachers"),
            ]
        ).drop("count")
        # Clip adj_teachers to minimum of 0
        schools_df = schools_df.with_columns([pl.col("adj_teachers").clip(lower_bound=0)])
    # Drop the region column
    teachers_df = teachers_df.drop("region")
    num_allocated = len(teachers_df.filter(pl.col("grade") != -1))
    print(
        f"  For {region_scales[geoid_scaling]}, allocated {num_allocated} teachers"
        f" out of {tot_reqd_teachers}"
    )
    return teachers_df, schools_df


@timer
def alloc_teachers_for_school_type(
    workers_df: pl.DataFrame, students_df: pl.DataFrame, schools_df: pl.DataFrame, school_type: str
) -> pl.DataFrame:
    printgreen(f"Allocating teachers for {school_type}")
    naics_code: int = -1
    # The number of students at each school will not exactly match the original schools data, so we
    # use the actual number of students we have allocated, and the original student/teacher ratio
    # to set the desired teacher counts for each school
    if school_type == "childcare":
        naics_categs = list(categ_types["pr_naics"].categories)
        naics_code = naics_categs.index("6244")
        schools_df = schools_df.filter(pl.col("level") == "C")
        students_df = students_df.filter(pl.col("grade") <= 3)
    elif school_type == "secondary":
        naics_categs = list(categ_types["pr_naics"].categories)
        naics_code = naics_categs.index("6111")
        schools_df = schools_df.filter(
            pl.col("level").is_in(["E", "EM", "EMH", "M", "MH", "H", "P", "PE", "PEM", "PEMH"])
        )
        students_df = students_df.filter((pl.col("grade") > 3) & (pl.col("grade") <= 17))
    elif school_type == "university":
        naics_categs = list(categ_types["pr_naics"].categories)
        naics_code = naics_categs.index("611")
        schools_df = schools_df.filter(pl.col("level") == "U")
        students_df = students_df.filter((pl.col("grade") >= 18) & (pl.col("grade") <= 19))
    else:
        raise_err(f"School_type {school_type} not valid")
    print(f"Number of schools to use {len(schools_df)}, number of students {len(students_df)}")
    # Count allocated students per school
    alloc_schools_df = (
        students_df.group_by("school_id", maintain_order=True)
        .agg(pl.len().alias("alloc_students"))
        .rename({"school_id": "id"})
    )
    # Join with schools data
    schools_df = schools_df.join(alloc_schools_df, on="id", how="inner")
    # Calculate adjustment ratios and adjusted teacher counts
    schools_df = schools_df.with_columns(
        [
            (pl.col("alloc_students") / pl.col("students")).alias("ratio"),
            (pl.col("teachers") * pl.col("alloc_students") / pl.col("students"))
            .ceil()
            .cast(pl.Int32)
            .alias("adj_teachers"),
        ]
    )
    dump_intermediate(schools_df, "schools_" + school_type)
    schools_df = schools_df.with_columns([pl.col("adj_teachers").alias("alloc_teachers")])
    # Get teachers with the appropriate NAICS code
    teachers_df = workers_df.filter(pl.col("naics") == naics_code)
    num_reqd_teachers = schools_df["adj_teachers"].sum()
    print(
        f"Found {len(teachers_df)} workers with NAICS code {naics_code} for "
        f"{num_reqd_teachers} required teachers, ratio {len(students_df) / num_reqd_teachers:.2f}"
    )
    scales = list(region_scales.keys())
    # Initialize teacher assignment columns
    teachers_df = teachers_df.with_columns(
        [pl.lit("").alias("school_id"), pl.lit(-1, dtype=pl.Int8).alias("grade")]
    )
    # Pick schools for teachers from decreasing resolution; the goal is to allocate teachers as
    # close to home as possible
    for scale in scales:
        avail_teachers = teachers_df.filter(pl.col("grade") == -1)
        teachers_df, schools_df = alloc_teachers_region(avail_teachers, schools_df, scale)
        assigned_df = teachers_df.filter(pl.col("grade") != -1)
        # dump_intermediate(assigned_df, "teachers_" + school_type + "_" + str(region_scales[scale]))
        # Update workers_df with assigned teachers
        # Create update DataFrame
        update_df = assigned_df.select(["id", "school_id", "work_geoid", "grade"])
        workers_df = workers_df.join(update_df, on="id", how="left", suffix="_new")
        workers_df = workers_df.with_columns(
            [
                pl.when(pl.col("school_id_new").is_not_null())
                .then(pl.col("school_id_new"))
                .otherwise(pl.col("school_id"))
                .alias("school_id"),
                pl.when(pl.col("work_geoid_new").is_not_null())
                .then(pl.col("work_geoid_new"))
                .otherwise(pl.col("work_geoid"))
                .alias("work_geoid"),
                pl.when(pl.col("grade_new").is_not_null())
                .then(pl.col("grade_new"))
                .otherwise(pl.col("grade"))
                .alias("grade"),
            ]
        ).drop(["school_id_new", "work_geoid_new", "grade_new"])
    num_alloced = len(workers_df.filter(pl.col("grade") != -1))
    if (num_reqd_teachers - num_alloced) > 0:
        warn(f"Failed to allocate {num_reqd_teachers - num_alloced} teachers")
    return workers_df


@timer
def allocate_teachers(
    workers_df: pl.DataFrame, students_df: pl.DataFrame, schools_df: pl.DataFrame
) -> pl.DataFrame:
    printgreen("Allocating teachers")
    # Filter schools to only include those in worker home geoids
    worker_geoids = set(workers_df["home_geoid"].unique().to_list())
    schools_filtered = len(schools_df)
    schools_df = schools_df.filter(pl.col("geoid").is_in(worker_geoids))
    if len(schools_df) != schools_filtered:
        print(
            f"Filtered out {schools_filtered - len(schools_df)} "
            f"schools not in worker home geoids"
        )
    for school_type in ["childcare", "secondary", "university"]:
        workers_df = alloc_teachers_for_school_type(
            workers_df, students_df, schools_df, school_type
        )
    return workers_df


def adjust_indexes(df: pl.DataFrame, output: str) -> pl.DataFrame:
    df = df.sort("id")
    orig_ids_df = df.select(
        [pl.col("id").alias("orig_id"), pl.arange(0, pl.len(), dtype=pl.Int64).alias("new_id")]
    )
    orig_ids_df.write_csv(output + ".idmap.csv", quote_style="necessary")
    # Replace ids with sequential integers
    df = df.with_columns([pl.arange(0, len(df), dtype=pl.Int64).alias("id")])
    # Convert school ids to unique integers
    # First, handle None and empty values
    df = df.with_columns(
        [
            pl.when(pl.col("school_id").is_null())
            .then(pl.lit(""))
            .otherwise(pl.col("school_id").cast(pl.Utf8))
            .alias("school_id")
        ]
    )
    # Get unique school IDs and create mapping
    unique_school_ids = sorted(df["school_id"].unique().to_list())
    school_id_map = {sid: idx for idx, sid in enumerate(unique_school_ids)}
    school_id_map[""] = 0
    print(f"Found {len(school_id_map)} unique school ids")
    # Map school IDs to integers
    df = df.with_columns(
        [
            pl.col("school_id")
            .map_elements(lambda x: school_id_map.get(x, 0), return_dtype=pl.Int64)
            .alias("school_id")
        ]
    )
    # Save zero indices for later
    zero_mask = pl.col("school_id") == 0
    # Make school IDs unique within each work_geoid using dense_rank
    df = df.with_columns(
        [
            pl.col("school_id")
            .rank(method="dense")
            .over("work_geoid")
            .cast(pl.Int16)
            .alias("school_id")
        ]
    )
    # Reset non-school rows to 0
    df = df.with_columns(
        [
            pl.when(zero_mask)
            .then(pl.lit(0, dtype=pl.Int16))
            .otherwise(pl.col("school_id"))
            .alias("school_id")
        ]
    )
    # Make household IDs unique within each home_geoid
    df = df.with_columns(
        [
            (pl.col("household_id").rank(method="dense").over("home_geoid") - 1)
            .cast(pl.Int16)
            .alias("household_id")
        ]
    )

    return df


def check_flows_correlation(df: pl.DataFrame, lodes_df: pl.DataFrame):
    # check that the actual allocated workers follow the lodes flows closely
    generated_df = df.group_by(["home_geoid", "work_geoid"], maintain_order=True).agg(
        pl.len().alias("total")
    )
    generated_df = generated_df.with_columns(
        [
            (pl.col("home_geoid").cast(pl.Utf8) + "-" + pl.col("work_geoid").cast(pl.Utf8)).alias(
                "key"
            )
        ]
    )
    lodes_df = lodes_df.with_columns(
        [(pl.col("h_geocode").cast(pl.Utf8) + "-" + pl.col("w_geocode").cast(pl.Utf8)).alias("key")]
    )
    merged_df = generated_df.join(lodes_df.select(["key", "count"]), on="key", how="full").select(
        ["key", "total", "count"]
    )
    merged_df = merged_df.with_columns(
        [pl.col("total").fill_null(0).cast(pl.Int32), pl.col("count").fill_null(0).cast(pl.Int32)]
    )
    dump_intermediate(merged_df, "worker_check_ods")
    corr = merged_df.select(pl.corr("total", "count")).item()
    print(
        f"LODES flows correlation: {corr:.3f} (generated count {merged_df['total'].sum()}, "
        f"actual count {merged_df['count'].sum()})"
    )
    if corr < CORR_CHECK_LEVEL:
        warn("Low correlation")


def polars_dtype_to_cpp(dtype: pl.DataType) -> str:
    """Convert Polars dtype to C++ type string"""
    if dtype == pl.Float32:
        return "float32"
    elif dtype == pl.Int8:
        return "int8"
    elif dtype == pl.Int16:
        return "int16"
    elif dtype == pl.Int32:
        return "int32"
    elif dtype == pl.Int64:
        return "int64"
    elif dtype == pl.Utf8:
        return "string"
    # Add other types as needed
    return str(dtype).lower()


@timer
def print_agents(df: pl.DataFrame, out_fname: str) -> tuple[list[int], list[int], list[str]]:
    df = df.sort("home_geoid")
    # Group by home_geoid and write to CSV
    buff = io.StringIO()
    foffsets = []
    home_pops = []
    home_geoids = []
    num_geoids = df["home_geoid"].n_unique()
    step = max(1, num_geoids // 10)
    out_fname_csv = out_fname + ".csv"
    printgreen(f"Writing CSV text data to {out_fname_csv}")
    # Group by home_geoid
    grouped = df.group_by("home_geoid", maintain_order=True)
    for i, (geoid_tuple, subset_df) in enumerate(grouped):
        # Extract geoid from tuple
        geoid = geoid_tuple[0] if isinstance(geoid_tuple, tuple) else geoid_tuple
        home_geoids.append(str(geoid))
        if i % step == 0:
            print(f"  GEOID {geoid} {i}", flush=True)
        foffsets.append(buff.tell())
        home_pops.append(len(subset_df))
        # Add marker column for CSV
        subset_with_marker = subset_df.with_columns([pl.lit("*").alias("marker")])
        # Reorder to put marker first
        cols = ["marker"] + [c for c in subset_df.columns]
        subset_with_marker = subset_with_marker.select(cols)
        # Write to buffer
        subset_with_marker.write_csv(buff, include_header=(i == 0), quote_style="necessary")
    # Write buffer to file
    with open(out_fname_csv, "w") as f:
        f.write(buff.getvalue())
        print(f"Wrote {len(df)} records in {buff.tell()} bytes")
    buff.close()
    return foffsets, home_pops, home_geoids


@timer
def print_agents_bin(df: pl.DataFrame, out_fname: str) -> tuple[list[int], list[int], list[str]]:
    # Sort by home_geoid to ensure consistent ordering
    df = df.sort("home_geoid")
    foffsets = []
    home_pops = []
    home_geoids = []
    grouped = df.group_by("home_geoid", maintain_order=True)
    num_geoids = df["home_geoid"].n_unique()
    step = max(1, num_geoids // 10)
    out_fname_bin = out_fname + ".bin"
    printgreen(f"Writing binary data to {out_fname_bin}")

    # Build struct format for entire row based on Polars dtypes
    struct_formats = {
        pl.Int64: "q",
        pl.Int32: "i",
        pl.Int16: "h",
        pl.Int8: "b",
        pl.Float32: "f",
        pl.Float64: "d",
    }

    # Get column dtypes in order
    dtypes = [df[col].dtype for col in df.columns]
    row_format = "".join(struct_formats[dt] for dt in dtypes)
    row_struct = struct.Struct(row_format)
    with open(out_fname_bin, "wb") as f:
        for i, (geoid_tuple, subset_df) in enumerate(grouped):
            # Extract geoid from tuple
            geoid = geoid_tuple[0] if isinstance(geoid_tuple, tuple) else geoid_tuple
            if i % step == 0:
                print(f"  GEOID {geoid} {i}/{num_geoids}", flush=True)
            home_geoids.append(str(geoid))
            foffsets.append(f.tell())
            home_pops.append(len(subset_df))
            # Convert subset to numpy array for efficient binary writing
            data_array = subset_df.to_numpy()
            for row in data_array:
                f.write(row_struct.pack(*row))
        file_size = f.tell()
        print(f"Wrote {len(df)} records in {file_size:,} bytes")

    return foffsets, home_pops, home_geoids


@timer
def compute_worker_populations(df: pl.DataFrame) -> tuple[pl.DataFrame, list[int]]:
    # Compute worker populations for each NAICS code
    work_geoids = df["work_geoid"].unique().to_list()
    # Get list of NAICS codes from categorical types
    naics_types = list(range(len(categ_types["pr_naics"].categories)))
    print(f"Found {len(work_geoids)} unique work GEOIDs and {len(naics_types)} unique NAICS codes")
    # Count workers by work_geoid and naics (excluding unemployed with naics == -1)
    work_geoids_df = (
        df.filter(pl.col("naics") != -1)
        .group_by(["work_geoid", "naics"], maintain_order=True)
        .agg(pl.len().alias("num"))
    )
    # Create full DataFrame with all combinations of work_geoid and naics
    # This ensures every GEOID has entries for all NAICS codes, even with count 0
    full_naics_df = pl.DataFrame(
        {
            "work_geoid": [geoid for geoid in work_geoids for _ in naics_types],
            "naics": naics_types * len(work_geoids),
        }
    )
    # Join with actual counts, filling missing values with 0
    work_geoids_pops_df = full_naics_df.join(
        work_geoids_df, on=["work_geoid", "naics"], how="left"
    ).with_columns([pl.col("num").fill_null(0).cast(pl.Int32)])
    return work_geoids_pops_df, naics_types


@timer
def print_index(
    df: pl.DataFrame,
    out_fname: str,
    foffsets: list[int],
    home_pops: list[int],
    home_geoids: list[str],
):
    work_geoids_pops_df, naics_types = compute_worker_populations(df)
    dump_intermediate(work_geoids_pops_df, out_fname + "_work_geoids_pops")
    work_geoids = df["work_geoid"].unique().to_list()
    step = max(1, len(work_geoids) // 10)
    out_fname_idx = out_fname + ".idx"
    printgreen(f"Writing block group indexes to {out_fname_idx}")
    with open(out_fname_idx, mode="w") as f:
        naics_descrs = list(categ_types["pr_naics"].categories)
        print("geoid foff h_pop w_pop", " ".join(naics_descrs), file=f)
        # print work-only GEOIDs
        if len(work_geoids) > len(home_geoids):
            only_work_geoids = list(set(work_geoids) - set(home_geoids))
            warn(f"Found {len(only_work_geoids)} work-only geoids out of {len(work_geoids)}")
            for geoid in only_work_geoids:
                work_pops = (
                    work_geoids_pops_df.filter(pl.col("work_geoid") == geoid)
                    .sort("naics")
                    .select("num")
                    .to_series()
                    .to_list()
                )
                tot_work_pop = sum(work_pops)
                print(geoid, 0, 0, tot_work_pop, " ".join(map(str, work_pops)), file=f)
        for i, geoid in enumerate(home_geoids):
            if i % step == 0:
                print(f"  GEOID {geoid} {i}", flush=True)
            work_pops = (
                work_geoids_pops_df.filter(pl.col("work_geoid") == int(geoid))
                .sort("naics")
                .select("num")
                .to_series()
                .to_list()
            )
            tot_work_pop = sum(work_pops)
            if tot_work_pop == 0:
                work_pops = [0] * len(naics_types)
            if len(work_pops) != len(naics_types):
                print(f"len work_pops {len(work_pops)} != len naics_types {len(naics_types)}")
                print(f"len naics_descrs {len(naics_descrs)}")
                for idx, p in enumerate(work_pops):
                    if p > 0:
                        print(idx, p, naics_descrs[idx])
                print("")
                print(f"Total work pop: {sum(work_pops)}")
                raise_err(
                    f"For geoid {geoid}, work pops != NAICS types, "
                    f"{len(work_pops)} != {len(naics_types)}"
                )
            print(
                geoid,
                foffsets[i],
                home_pops[i],
                tot_work_pop,
                " ".join(map(str, work_pops)),
                file=f,
            )


def sanity_checks(df: pl.DataFrame):
    students_df = df.filter((pl.col("grade") != -1) & (pl.col("naics") == -1))
    mismatches = students_df.filter(pl.col("school_id") == 0)
    if len(mismatches) > 0:
        warn(f"There are {len(mismatches)} students with no school_id")
    teachers_df = df.filter((pl.col("naics") != -1) & (pl.col("grade") != -1))
    mismatches = teachers_df.filter(pl.col("school_id") == 0)
    if len(mismatches) > 0:
        warn(f"There are {len(mismatches)} teachers with no school_id")
    workers_df = df.filter((pl.col("grade") == -1) & (pl.col("naics") != -1))
    mismatches = workers_df.filter(pl.col("school_id") != 0)
    if len(mismatches) > 0:
        warn(f"There are {len(mismatches)} workers with a school_id")
    unemp_df = df.filter((pl.col("grade") == -1) & (pl.col("naics") == -1))
    mismatches = unemp_df.filter(pl.col("school_id") != 0)
    if len(mismatches) > 0:
        warn(f"There are {len(mismatches)} unemployed agents with a school_id")
    mismatches = df.filter(
        (pl.col("naics") == -1)
        & (pl.col("grade") == -1)
        & (pl.col("home_geoid") != pl.col("work_geoid"))
    )
    if len(mismatches) > 0:
        warn(f"There are {len(mismatches)} unemployed agents with differing home and dest geoids")


def align_to_schema(
    df: pl.DataFrame, col_order: list[str], common_schema: dict[str, pl.DataType]
) -> pl.DataFrame:
    return df.select(
        [
            (
                pl.col(c).cast(common_schema[c])
                if c in df.columns
                else pl.lit(None).cast(common_schema[c]).alias(c)
            )
            for c in col_order
        ]
    )


def concat_all(
    workers_df: pl.DataFrame, students_df: pl.DataFrame, unemp_df: pl.DataFrame
) -> pl.DataFrame:
    # Ensure column order and types before concat
    all_cols = set(workers_df.columns) | set(students_df.columns) | set(unemp_df.columns)
    col_order = sorted(list(all_cols))
    # Get common schema again (types may have changed after teacher allocation)
    common_schema = {}
    for col in col_order:
        if col in workers_df.columns:
            common_schema[col] = workers_df[col].dtype
        elif col in students_df.columns:
            common_schema[col] = students_df[col].dtype
        else:
            common_schema[col] = unemp_df[col].dtype
    # Apply schema to all DataFrames
    workers_df = align_to_schema(workers_df, col_order, common_schema)
    students_df = align_to_schema(students_df, col_order, common_schema)
    unemp_df = align_to_schema(unemp_df, col_order, common_schema)
    return pl.concat([workers_df, students_df, unemp_df])


@timer
def main():
    args = get_args()
    np.random.seed(args.rseed)
    upop_df = load_upop_feather_files(args.upop_files, args.output)
    upop_df = process_upop(upop_df, args.output)
    lodes_df = get_lodes_groups(args.lodes_files)
    schools_df = load_schools(args.schools_file)
    # filter out those schools that don't have the same geoid as the home geoids
    schools_df = schools_df.filter(pl.col("geoid").is_in(upop_df["home_geoid"].unique().to_list()))
    workers_df, students_df, schools_df, unemp_df = generate_nt_dt(schools_df, upop_df, lodes_df)
    check_flows_correlation(workers_df, lodes_df)
    # workers_df.write_ipc("workers_df.feather")
    # students_df.write_ipc("students_df.feather")
    # schools_df.write_ipc("schools_df.feather")
    # unemp_df.write_ipc("unemp_df.feather")
    # Capture return values from allocate_teachers
    workers_df = allocate_teachers(workers_df, students_df, schools_df)
    teachers_df = workers_df.filter(pl.col("grade") != -1)
    check_school_id_correlation(
        students_df.filter(pl.col("school_id") != ""), schools_df, "Students"
    )
    check_school_id_correlation(teachers_df, schools_df, "Teachers")
    check_school_geoid_correlation(
        students_df.filter(pl.col("school_id") != ""), schools_df, "Students"
    )
    check_school_geoid_correlation(teachers_df, schools_df, "Teachers")
    print_school_counts(students_df, workers_df)
    df = concat_all(workers_df, students_df, unemp_df)
    df = df.with_columns([pl.col("grade").cast(pl.Int8)])
    # reorder the columns so that we have the largest variables first
    df = df.select(
        [
            "id",
            "home_geoid",
            "work_geoid",
            "naics",
            "household_id",
            "school_id",
            "age",
            "sex",
            "race",
            "travel",
            "veh_occ",
            "grade",
        ]
    )
    # Set the location types
    df = df.with_columns(
        [
            pl.col("home_geoid").cast(pl.Int64),
            pl.col("work_geoid").fill_null("-1").cast(pl.Int64),
        ]
    )
    # Set work_geoid to home_geoid where work_geoid is -1
    df = df.with_columns(
        [
            pl.when(pl.col("work_geoid") == -1)
            .then(pl.col("home_geoid"))
            .otherwise(pl.col("work_geoid"))
            .alias("work_geoid")
        ]
    )
    dump_intermediate(df, args.output + "_nt_dt")
    df = adjust_indexes(df, args.output)
    df = df.with_columns(
        [
            pl.when((pl.col("grade") == -1))
            .then(pl.lit(0, dtype=pl.Int16))
            .otherwise(pl.col("school_id"))
            .alias("school_id")
        ]
    )
    print("Fields are:")
    for name, dtype in df.schema.items():
        print(f"  {name:12s}  {dtype}")
    sanity_checks(df)
    # print_cpp_header(df)
    foffsets, home_pops, home_geoids = print_agents_bin(df, args.output + "-bin")
    print_index(df, args.output + "-bin", foffsets, home_pops, home_geoids)

    foffsets, home_pops, home_geoids = print_agents(df, args.output)
    print_index(df, args.output, foffsets, home_pops, home_geoids)


if __name__ == "__main__":
    main()
