#!/usr/bin/env -S python -u

# This script takes .feather files generated by UrbanPop, including both person details and
# daytime-nightime assignments, and converts them into a csv file with the information that is
# needed for ExaEpi. It can use either daytime/nightime files generated by UrbanPop, or it can
# generate the daytime/nightime flows from LODES and school data. This script also generates a c++
# header file containing the structure of the data, including functions for reading and writing
# the data.

import gc
import os
import sys
import pandas as pd
import numpy as np
import argparse
import configparser
import glob
from colorama import Fore
import psutil
from pandas.api.types import CategoricalDtype
from get_schools import timer
import get_schools


DUMP_INTERMEDIATES = True

# note: missing category indexes are written as -1
# we could extract these from the dataset, but then they will not be in a suitable order, even with
# sorting so we predefine and check for values in the data that are not listed here
categ_types = {
    "hh_type": CategoricalDtype(categories=["hh", "gq"]),
    "hh_living_arrangement": CategoricalDtype(
        categories=["married", "male_no_spouse", "female_no_spouse", "alone", "not_alone"]
    ),
    "hh_has_kids": CategoricalDtype(categories=["no", "yes"]),
    "hh_dwg": CategoricalDtype(
        # fmt: off
        categories=[
            "single_fam_detach", "single_fam_attach", "2_unit", "3_4_unit", "5_9_unit",
            "10_19_unit", "20_49_unit", "GE50_unit", "mob_home", "other",
        ]
        # fmt: on
    ),
    "hh_tenure": CategoricalDtype(categories=["own", "rent", "other"]),
    "hh_vehicles": CategoricalDtype(categories=["01", "02", "03", "04", "05", "GE06"]),
    "pr_sex": CategoricalDtype(categories=["female", "male"]),
    "pr_race": CategoricalDtype(
        categories=["white", "blk_af_amer", "asian", "native_amer", "pac_island", "other", "mult"]
    ),
    "pr_hsplat": CategoricalDtype(categories=["no", "yes"]),
    "pr_ipr": CategoricalDtype(
        categories=["L050", "050_099", "100_124", "125_149", "150_184", "185_199", "GE200"]
    ),
    "pr_emp_stat": CategoricalDtype(categories=["not.in.force", "unemp", "employed", "mil"]),
    "pr_travel": CategoricalDtype(
        # fmt: off
        categories=[
            "car_truck_van", "public_transportation", "bicycle", "walked", "motorcycle", "taxicab",
            "other", "wfh",
        ]
        # fmt: on
    ),
    "pr_veh_occ": CategoricalDtype(categories=["drove_alone", "carpooled"]),
    "pr_grade": CategoricalDtype(
        # fmt: off
        categories=[
            "childcare", "preschl", "kind", "1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th",
            "9th", "10th", "11th", "12th", "undergrad", "grad",
        ]
        # fmt: on
    ),
    "role": CategoricalDtype(categories=["nope", "worker", "student"]),
    "naics": CategoricalDtype(
        # fmt: off
        categories=[
            "111", "112", "113", "1133", "114", "115", "211", "2121", "2122", "2123", "213",
            "22", "221", "2211", "2212", "2213", "22132", "23", "3", "31", "311", "3113",
            "3114", "3115", "3116", "3118", "311811", "3121", "3122", "3131", "3132", "3133",
            "314", "31411", "315", "316", "3162", "3211", "3212", "3219", "32199", "3221",
            "3222", "32221", "3231", "3241", "32411", "325", "3252", "3253", "3254", "3255",
            "3256", "3261", "3262", "32621", "327", "32711", "327120", "3272", "3279", "33",
            "331", "3313", "3314", "3315", "332", "3321", "3322", "3327", "3328", "33299",
            "333", "3331", "33311", "3333", "3335", "3336", "334", "3341", "3345", "335",
            "3352", "336", "33641", "3365", "3366", "3369", "337", "3391", "3399", "4", "42",
            "4231", "4232", "4233", "4234", "4235", "4236", "4237", "4238", "4239", "42393",
            "424", "4241", "4243", "4244", "4245", "4247", "4248", "4249", "42491", "4251",
            "4411", "4412", "4413", "442", "443141", "443142", "4441", "44413", "4442",
            "44511", "44512", "4452", "4453", "446", "44611", "447", "4481", "44821", "4483",
            "4511", "45113", "45114", "45121", "45221", "4523", "4531", "45321", "45322",
            "4533", "4539", "454110", "4542", "454310", "45439", "481", "482", "483", "484",
            "485", "4853", "486", "487", "488", "491", "492", "493", "5111", "51111", "5112",
            "5121", "5122", "515", "517", "517311", "5182", "5191", "51912", "51913", "52",
            "522", "5221", "5241", "5242", "53", "531", "5313", "532", "5321", "5411", "5412",
            "5413", "5414", "5415", "5416", "5417", "5418", "5419", "54194", "55", "561",
            "5613", "5614", "5615", "5616", "5617", "56173", "562", "611", "6111", "621",
            "6211", "6212", "6213", "62131", "62132", "6214", "6216", "622", "6222", "623",
            "6231", "6241", "6242", "6243", "6244", "711", "7111", "7112", "7115", "712",
            "713", "71395", "721", "7211", "722", "7224", "8111", "811192", "8112", "8113",
            "8114", "8121", "812111", "812112", "8122", "8123", "8129", "813", "8131", "8139",
            "81393", "814", "92", "9211", "92113", "92119", "923", "928"
        ]
        # fmt: on
    ),
}


def warn(fmt_str, *args):
    print(f"{Fore.RED}WARNING: {fmt_str}{Fore.RESET}" % args)


def get_args():
    """Process command line arguments and configuration file settings.

    This function implements a two-stage argument parsing system that allows arguments
    to be specified either via command line or through a configuration file. The process works as follows:
    Arguments can be provided in two ways:
    1. Command line: python script.py --output out.csv --upop_files data/*.feather
    2. Config file:  python script.py -c config.cfg
       Where config.cfg contains:
       [main]
       output = out.csv
       upop_files = data/*.feather

    Returns:
        argparse.Namespace: Parsed arguments with all values resolved
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", "-o", help="Output file")
    parser.add_argument(
        "--upop_files", "-f", nargs="+", required=True, help="UrbanPop feather files"
    )
    # parser.add_argument(
    #    "--shape_files",
    #    "-e",
    #    nargs="+",
    #    required=True,
    #    default=[],
    #    help="Census block group shape files. Available from\n"
    #    + "https://www.census.gov/cgi-bin/geo/shapefiles/index.php?year=2010&layergroup=Block+Groups",
    # )
    parser.add_argument(
        "--lodes_files",
        "-l",
        nargs="+",
        required=True,
        default=[],
        help="LODES7 origin-destination (OD) files in CSV format. Not needed if UrbanPop nighttime/daytime files are used",
    )
    parser.add_argument(
        "--schools_file",
        "-s",
        required=True,
        default="",
        help="File containing schools data in CSV format. Not needed if UrbanPop nighttime/daytime files are used",
    )
    parser.add_argument(
        "--up_nt_dt_files",
        "-n",
        nargs="+",
        default=[],
        help="Files containing nighttime/daytime data from UrbanPop in feather format. Used instead of LODES files",
    )
    parser.add_argument("--rseed", "-r", default=29, type=int, help="Random seed")

    main_args = {}
    reqd_args = []
    file_lists = []
    for action in parser._actions:
        main_args[action.dest] = action.default
        if action.required:
            reqd_args.append(action.dest)
        if action.nargs == "+":
            file_lists.append(action.dest)

    cfg_parser = argparse.ArgumentParser(
        description="Convert UrbanPop feather files to a csv file for ExaEpi input", add_help=False
    )
    cfg_parser.add_argument("-c", "--config", help="Config file", metavar="FILE")
    args, remaining_argv = cfg_parser.parse_known_args()
    if args.config:
        cfg = configparser.ConfigParser()
        cfg.read([args.config])
        for item in cfg.items("main"):
            if item[0] not in main_args:
                warn(f"{item[0]} not recognized as a valid argument, ignoring it")
        main_args.update(dict(cfg.items("main")))
        for arg in main_args:
            if arg in reqd_args and (main_args[arg] == "" or main_args[arg] == []):
                raise ValueError(
                    f"Required argument {arg} not specified in config file {args.config}"
                )
            if arg in file_lists and main_args[arg] != []:
                main_args[arg] = glob.glob(main_args[arg])

    new_parser = argparse.ArgumentParser(parents=[cfg_parser])
    for action in parser._actions:
        if action.option_strings[0] == "-h":
            continue
        # Only pass non-None strings to add_argument
        add_arg_kwargs = {
            "dest": action.dest,
            "default": main_args[action.dest],
            "nargs": action.nargs,
            "help": action.help,
            "required": (
                True
                if action.required
                and (
                    main_args[action.dest] == ""
                    or main_args[action.dest] == []
                    or main_args[action.dest] is None
                )
                else False
            ),
        }
        if action.type is not None:
            add_arg_kwargs["type"] = action.type
        new_parser.add_argument(
            *[opt for opt in action.option_strings if opt is not None],
            **add_arg_kwargs,
        )
    args = new_parser.parse_args(remaining_argv)
    print(Fore.CYAN, "Options:", sep="")
    for arg, value in args.__dict__.items():
        print(f"  {arg:20s} {value}")
    print(Fore.RESET, end="")
    return args


@timer
def dump_intermediate(df, fname):
    if DUMP_INTERMEDIATES:
        print(f"Dumping intermediate file {fname + ".intermediate.csv"}")
        df.to_csv(fname + ".intermediate.csv", index=False)


def load_upop_feather_files(fnames, out_fname):
    print(f"Reading UrbanPop data from {len(fnames)} files")
    dfs = []
    df = pd.DataFrame()
    chunk_size = int(len(fnames) / 10)
    for i, fname in enumerate(fnames):
        df_read = pd.read_feather(fname)
        dfs.append(df_read)
        if i == len(fnames) - 1 or i % chunk_size == 0:
            dfs.append(df)
            df = pd.concat(dfs, ignore_index=True)
            del dfs
            dfs = []
            gc.collect()
            mem_used = float(psutil.Process(os.getpid()).memory_info().rss) / 1024 / 1024 / 1024
            mem_of_df = float(df.memory_usage().sum()) / 1024 / 1024 / 1024
            if chunk_size > 0:
                print(f"  {int(i / chunk_size)}:", end="")
            print(f" read {fname}, memory RSS {mem_used:0.2f} G, memory of df {mem_of_df:0.2f} G")

    print(f"Read {len(df.index)} records")
    # need to sort to ensure the order is the same between the population files and the
    # daytime/nighttime files
    df.sort_values(by=["p_id"], inplace=True)
    # dump_intermediate(df, out_fname + ".upop")
    return df


@timer
def set_types(df):
    # treat the NAICS types as strings for later sorting
    df.pr_naics = df.pr_naics.astype("str")
    df.h_id = df.h_id.str.split("-").str[-1].astype("int32")
    for field_type in df:
        if field_type in categ_types:
            # compare the list with the unique to make sure we haven't found anything not in our
            # predefined list
            categs_found = list(df[field_type].unique())
            categs_expected = list(categ_types[field_type].categories)
            missing = [
                x for x in categs_found if x not in categs_expected and x != "" and x is not None
            ]
            if missing:
                warn(f"Found missing categories for {field_type}: {missing}")
            df[field_type] = df[field_type].astype(categ_types[field_type]).cat.codes
        else:
            if df.dtypes[field_type] == object:
                df[field_type] = df[field_type].astype("string")
            else:
                # this converts all float to int
                max_val = df[field_type].max()
                if max_val < 128:
                    df[field_type] = df[field_type].astype("int8")
                elif max_val < 2**15:
                    df[field_type] = df[field_type].astype("int16")
                elif max_val < 2**31:
                    df[field_type] = df[field_type].astype("int32")
                else:
                    df[field_type] = df[field_type].astype("int64")


def rename_fields(df):
    df.rename(columns={"geoid": "home_geoid", "h_id": "household_id", "p_id": "id"}, inplace=True)
    for col in df.columns:
        if col.startswith("pr_"):
            df.rename(columns={col: col[3:]}, inplace=True)
        elif col.startswith("h_"):
            df.rename(columns={col: "home_" + col[2:]}, inplace=True)
        elif col.startswith("w_"):
            df.rename(columns={col: "work_" + col[2:]}, inplace=True)
        elif col.startswith("hh_"):
            df.rename(columns={col: "household_" + col[3:]}, inplace=True)


def get_level_from_age(min_age, max_age):
    if min_age >= 18:
        return "U"
    if max_age == 3:
        return "C"
    return get_schools.get_level_from_age(min_age, max_age)


@timer
def process_upop_nt_dt(up_nt_dt_files, upop_df):
    df = pd.DataFrame()
    print("Loading UrbanPop nighttime/daytime files")
    # get NAICS from base UrbanPop data - it gives more detailed categories
    for fname in up_nt_dt_files:
        region_df = pd.read_feather(fname)[
            ["p_id", "role", "orig_geoid", "dest_geoid", "school_id"]
        ].astype({"orig_geoid": "str", "dest_geoid": "str"})
        df = pd.concat([df, region_df], ignore_index=True)
    print(f"Loaded {len(df)} entries from {len(up_nt_dt_files)} files")
    df.sort_values(by=["p_id"], inplace=True)
    df.rename(
        columns={"p_id": "id", "orig_geoid": "home_geoid", "dest_geoid": "work_geoid"}, inplace=True
    )
    upop_len = len(upop_df)
    upop_df = upop_df[upop_df["id"].isin(df["id"])].reset_index(drop=True)
    if len(upop_df) != upop_len:
        print(f"Dropped {upop_len - len(upop_df)} entries not found in daytime/nightime")
    if not np.array_equal(df.id.to_numpy(), upop_df.id.to_numpy()):
        print(f"ids: {df.id.to_numpy()[:10]}\n{upop_df.id.to_numpy()[:10]}")
        err_str = f"{Fore.RED}Mismatched p_ids for population vs daytime/nightime{Fore.RESET}"
        raise RuntimeError(err_str)
    if not np.array_equal(df.home_geoid.to_numpy(), upop_df.home_geoid.to_numpy()):
        print(f"home geoids: {df.home_geoid.to_numpy()[:10]}\n{upop_df.home_geoid.to_numpy()[:10]}")
        err_str = f"{Fore.RED}Mismatched geoids for population vs daytime/nightime{Fore.RESET}"
        raise RuntimeError(err_str)
    # FIXME: we should probably check the grades too

    df.drop(columns=["home_geoid"], inplace=True)
    df = df.merge(upop_df, on="id", how="outer")
    print(df.dtypes)

    workers_df = df[df.role == "worker"].reset_index(drop=True)
    workers_df["grade"] = -1
    dump_intermediate(workers_df, "workers_from_upop_nt_dt")

    unemp_df = df[df.role == "nope"].reset_index(drop=True)
    unemp_df["grade"] = -1
    dump_intermediate(unemp_df, "unemployed_from_upop_nt_dt")

    students_df = df[df.role == "student"].reset_index(drop=True)
    dump_intermediate(students_df, "students_from_upop_nt_dt")

    schools_df = (
        students_df.groupby(["school_id", "work_geoid"]).size().reset_index(name="students")
    )
    schools_df.rename(columns={"school_id": "id", "work_geoid": "geoid"}, inplace=True)
    # we have estimated ratios for teachers per students at each level
    teacher_ratios = [[18, 19, 5], [14, 17, 15], [11, 13, 13], [5, 10, 12], [3, 4, 7]]
    for ratio in teacher_ratios:
        idx = (students_df.grade >= ratio[0]) & (students_df.grade <= ratio[1])
        schools_df.loc[idx, "teachers"] = np.ceil(schools_df.students / ratio[2]).astype(int)

    schools_df["min_age"] = students_df.groupby(["school_id", "work_geoid"], as_index=False)[
        "grade"
    ].min()["grade"]
    schools_df["max_age"] = students_df.groupby(["school_id", "work_geoid"], as_index=False)[
        "grade"
    ].max()["grade"]
    schools_df["level"] = list(
        map(get_level_from_age, schools_df["min_age"], schools_df["max_age"])
    )
    schools_df = schools_df[["id", "students", "teachers", "level", "geoid"]]
    dump_intermediate(schools_df, "schools_with_geoids_upop_nt_dt")
    return workers_df, students_df, schools_df, unemp_df


@timer
def process_upop(df, out_fname):
    print("Processing UrbanPop data")
    # only include these fields in the output csv and c++ structure
    include_fields = {
        "p_id",
        # "pums_id",
        "h_id",
        "geoid",
        # "hh_size",
        # "hh_type",
        # "hh_living_arrangement",
        # "hh_age",
        # "hh_has_kids",
        # "hh_income",
        # "hh_nb_wrks",
        # "hh_nb_non_wrks",
        # "hh_nb_adult_wrks",
        # "hh_nb_adult_non_wrks",
        # "hh_dwg",
        # "hh_tenure",
        # "hh_vehicles",
        "pr_age",
        "pr_sex",
        "pr_race",
        # "pr_hsplat",
        # "pr_ipr",
        "pr_naics",
        "pr_emp_stat",
        "pr_travel",
        "pr_veh_occ",
        "pr_commute",
        "pr_grade",
    }
    df.drop(columns=set(df.columns.values) - include_fields, inplace=True)
    # dump_intermediate(df, out_fname + ".upop.purged")
    set_types(df)
    rename_fields(df)


@timer
def get_lodes_groups(lodes_fnames):
    # Origin-Destination (OD) File Structure (LODES flows)
    # Pos Variable Type Explanation
    # 1 w_geocode Char15 Workplace Census Block Code
    # 2 h_geocode Char15 Residence Census Block Code
    # 3 S000 Num Total number of jobs
    # 4 SA01 Num Number of jobs of workers age 29 or younger
    # 5 SA02 Num Number of jobs for workers age 30 to 54
    # 6 SA03 Num Number of jobs for workers age 55 or older
    # 7 SE01 Num Number of jobs with earnings $1250/month or less
    # 8 SE02 Num Number of jobs with earnings $1251/month to $3333/month
    # 9 SE03 Num Number of jobs with earnings greater than $3333/month
    # 10 SI01 Num Number of jobs in Goods Producing industry sectors
    # 11 SI02 Num Number of jobs in Trade, Transportation, and Utilities industry sectors
    # 12 SI03 Num Number of jobs in All Other Services industry sectors
    # 13 createdate Char Date on which data was created, formatted as YYYYMMDD
    df = pd.DataFrame()
    for lodes_fname in lodes_fnames:
        print("Loading", lodes_fname)
        lodes_df = pd.read_csv(
            lodes_fname, dtype={"w_geocode": str, "h_geocode": str, "S000": int}
        )[["w_geocode", "h_geocode", "S000"]]
        # print("Loaded", len(lodes_df), "entries")
        # truncate geoids to first 12, i.e. just census block groups
        lodes_df.h_geocode = lodes_df.h_geocode.str[:12]
        lodes_df.w_geocode = lodes_df.w_geocode.str[:12]
        lodes_df = (
            lodes_df.groupby(["w_geocode", "h_geocode"])
            .S000.sum()
            .reset_index()
            .rename(columns={0: "count"})
        )
        dump_intermediate(lodes_df, lodes_fname + "-short")
        df = pd.concat([df, lodes_df], ignore_index=True)
    return df


@timer
def set_childcare(upop_df):
    print(Fore.GREEN + "Setting childcare" + Fore.RESET)
    # UrbanPop doesn't have allocations to childcare outside of PK in schools, so we randomly assign agents under age 5 not in PK
    # to childcare. According to NCES, 32% of under 1 year, 47% of 1-2 yrs and 83 of 3-5 yrs are in center-based care
    PROBS = {0: 0.32, 1: 0.47, 2: 0.47, 3: 0.83, 4: 0.83}
    df = upop_df.copy()
    for age in np.arange(0, 5):
        is_candidate = (df.pr_grade == "") & (df.pr_age == age)
        num_candidates = int(len(df[is_candidate]) * PROBS[age])
        to_set = df[is_candidate].sample(n=num_candidates, replace=False)
        print("  Age", age, "set", len(to_set), "out of", len(df[is_candidate]))
        df.loc[to_set.index, "pr_grade"] = "childcare"

    print("Set", len(df[(df.pr_grade.str.startswith("childcare"))]), "agents to childcare")
    dump_intermediate(df, "childcare")
    return df


@timer
def load_schools(fname):
    print("Loading schools from", fname)
    schools_df = pd.read_csv(fname, low_memory=False, dtype={"geoid": str})
    print(
        "Loaded",
        len(schools_df),
        "entries:",
        schools_df.students.sum(),
        "students,",
        schools_df.teachers.sum(),
        "teachers",
    )
    if DUMP_INTERMEDIATES:
        schools_df.to_csv("schools.csv", sep="\t", index=False)
    return schools_df


@timer
def generate_nt_dt(schools_file, upop_df, lodes_df):
    # randomly allocate some young agents to childcare
    upop_df = set_childcare(upop_df)
    # now split into students, workers and unemployed.
    # Note that the UrbanPop nt/dt data classifies mil as unemployed (nope); because they don't commute?
    # UrbanPop nt/dt sometimes classifies employed people with assigned grades as students, not workers. Not sure when/why
    # it does this. We will assume that employed agents with assigned grades are students if they are under 25 in age
    is_employed = (upop_df.pr_emp_stat == "employed") & (
        (upop_df.pr_grade == "") | (upop_df.pr_age >= 25)
    )
    in_school = (upop_df.pr_grade != "") & ~is_employed
    students_df = upop_df[in_school].copy()
    workers_df = upop_df[is_employed]
    unemp_df = upop_df[~is_employed & ~in_school]
    tot = len(workers_df) + len(students_df) + len(unemp_df)
    print("Counts:")
    print("  workers:   ", len(workers_df))
    print("  students:  ", len(students_df))
    print("  unemployed:", len(unemp_df))
    print("  total:     ", tot)
    if tot != len(upop_df):
        print(
            "ERROR: total agents mismatch, allocated",
            tot,
            "but found",
            len(upop_df),
            "in UrbanPop feather files",
        )

    workers_nt_dt_df = pd.DataFrame()  # alloc_workers(lodes_df, workers_df)

    schools_df = load_schools(schools_file)
    students_nt_dt_df = pd.DataFrame()  # alloc_students(schools_df, students_df)

    unemp_df["work_geoid"] = unemp_df["home_geoid"]
    unemp_df["school_id"] = ""
    unemp_df["role"] = "nope"
    unemp_df["grade"] = ""

    return workers_nt_dt_df, students_nt_dt_df, schools_df, unemp_df


@timer
def main():
    args = get_args()
    np.random.seed(args.rseed)

    upop_df = load_upop_feather_files(args.upop_files, args.output)
    process_upop(upop_df, args.output)
    lodes_df = get_lodes_groups(args.lodes_files)
    if args.up_nt_dt_files:
        workers_df, students_df, schools_df, unemp_df = process_upop_nt_dt(
            args.up_nt_dt_files, upop_df
        )
    else:
        workers_df, students_df, schools_df, unemp_df = generate_nt_dt(
            args.schools_file, upop_df, lodes_df
        )


if __name__ == "__main__":
    main()
