#!/usr/bin/env -S python -u

# This script takes .feather files generated by UrbanPop, including both person details and
# daytime-nightime assignments, and converts them into a csv file with the information that is
# needed for ExaEpi. It can use either daytime/nightime files generated by UrbanPop, or it can
# generate the daytime/nightime flows from LODES and school data. This script also generates a c++
# header file containing the structure of the data, including functions for reading and writing
# the data.

import gc
import io
from multiprocessing import Pool
from functools import partial
from multiprocessing.pool import ThreadPool
import os
import sys
import pandas as pd
import numpy as np
import argparse
import configparser
import struct
import glob
from colorama import Fore
import psutil
from pandas.api.types import CategoricalDtype
from get_schools import timer
import get_schools


DUMP_INTERMEDIATES = False

# note: missing category indexes are written as -1
# we could extract these from the dataset, but then they will not be in a suitable order, even with
# sorting so we predefine and check for values in the data that are not listed here
categ_types = {
    "hh_type": CategoricalDtype(categories=["hh", "gq"]),
    "hh_living_arrangement": CategoricalDtype(
        categories=["married", "male_no_spouse", "female_no_spouse", "alone", "not_alone"]
    ),
    "hh_has_kids": CategoricalDtype(categories=["no", "yes"]),
    "hh_dwg": CategoricalDtype(
        # fmt: off
        categories=[
            "single_fam_detach", "single_fam_attach", "2_unit", "3_4_unit", "5_9_unit",
            "10_19_unit", "20_49_unit", "GE50_unit", "mob_home", "other",
        ]
        # fmt: on
    ),
    "hh_tenure": CategoricalDtype(categories=["own", "rent", "other"]),
    "hh_vehicles": CategoricalDtype(categories=["01", "02", "03", "04", "05", "GE06"]),
    "pr_sex": CategoricalDtype(categories=["female", "male"]),
    "pr_race": CategoricalDtype(
        categories=["white", "blk_af_amer", "asian", "native_amer", "pac_island", "other", "mult"]
    ),
    "pr_hsplat": CategoricalDtype(categories=["no", "yes"]),
    "pr_ipr": CategoricalDtype(
        categories=["L050", "050_099", "100_124", "125_149", "150_184", "185_199", "GE200"]
    ),
    "pr_emp_stat": CategoricalDtype(categories=["not.in.force", "unemp", "employed", "mil"]),
    "pr_travel": CategoricalDtype(
        # fmt: off
        categories=[
            "car_truck_van", "public_transportation", "bicycle", "walked", "motorcycle", "taxicab",
            "other", "wfh",
        ]
        # fmt: on
    ),
    "pr_veh_occ": CategoricalDtype(categories=["drove_alone", "carpooled"]),
    "pr_grade": CategoricalDtype(
        # fmt: off
        categories=[
            "childcare", "preschl", "kind", "1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th",
            "9th", "10th", "11th", "12th", "undergrad", "grad",
        ]
        # fmt: on
    ),
    "role": CategoricalDtype(categories=["nope", "worker", "student"]),
    "pr_naics": CategoricalDtype(
        # fmt: off
        categories=[
            "111", "112", "113", "1133", "114", "115", "211", "2121", "2122", "2123", "213",
            "22", "221", "2211", "2212", "2213", "22132", "23", "3", "31", "311", "3113",
            "3114", "3115", "3116", "3118", "311811", "3121", "3122", "3131", "3132", "3133",
            "314", "31411", "315", "316", "3162", "3211", "3212", "3219", "32199", "3221",
            "3222", "32221", "3231", "3241", "32411", "325", "3252", "3253", "3254", "3255",
            "3256", "3261", "3262", "32621", "327", "32711", "327120", "3272", "3279", "33",
            "331", "3313", "3314", "3315", "332", "3321", "3322", "3327", "3328", "33299",
            "333", "3331", "33311", "3333", "3335", "3336", "334", "3341", "3345", "335",
            "3352", "336", "33641", "3365", "3366", "3369", "337", "3391", "3399", "4", "42",
            "4231", "4232", "4233", "4234", "4235", "4236", "4237", "4238", "4239", "42393",
            "424", "4241", "4243", "4244", "4245", "4247", "4248", "4249", "42491", "4251",
            "4411", "4412", "4413", "442", "443141", "443142", "4441", "44413", "4442",
            "44511", "44512", "4452", "4453", "446", "44611", "447", "4481", "44821", "4483",
            "4511", "45113", "45114", "45121", "45221", "4523", "4531", "45321", "45322",
            "4533", "4539", "454110", "4542", "454310", "45439", "481", "482", "483", "484",
            "485", "4853", "486", "487", "488", "491", "492", "493", "5111", "51111", "5112",
            "5121", "5122", "515", "517", "517311", "5182", "5191", "51912", "51913", "52",
            "522", "5221", "5241", "5242", "53", "531", "5313", "532", "5321", "5411", "5412",
            "5413", "5414", "5415", "5416", "5417", "5418", "5419", "54194", "55", "561",
            "5613", "5614", "5615", "5616", "5617", "56173", "562", "611", "6111", "621",
            "6211", "6212", "6213", "62131", "62132", "6214", "6216", "622", "6222", "623",
            "6231", "6241", "6242", "6243", "6244", "711", "7111", "7112", "7115", "712",
            "713", "71395", "721", "7211", "722", "7224", "8111", "811192", "8112", "8113",
            "8114", "8121", "812111", "812112", "8122", "8123", "8129", "813", "8131", "8139",
            "81393", "814", "92", "9211", "92113", "92119", "923", "928"
        ]
        # fmt: on
    ),
}

CORR_CHECK_LEVEL = 0.8

region_scales = {
    12: "blockgroup",
    11: "tract",
    10: "county_subdiv",
    7: "census_places",
    5: "county",
    2: "state",
}

age_levels = {
    "C": [3, 3],
    "P": [4, 4],
    "E": [5, 10],
    "M": [11, 13],
    "H": [14, 17],
    "U": [18, 19],
    "PE": [4, 10],
    "PEM": [4, 13],
    "PEMH": [4, 17],
    "EM": [5, 13],
    "EMH": [5, 17],
    "MH": [11, 17],
}

# these are teacher ratios used to add teachers to the UrbanPop day/night data, *not* for the
# generated data
teacher_ratios = {
    "C": 6.8,
    "P": 12.8,
    "E": 12.8,
    "M": 14.0,
    "H": 15.0,
    "U": 5.5,
    "PE": 12.8,
    "PEM": 13.5,
    "PEMH": 14.2,
    "EM": 13.5,
    "EMH": 14.2,
    "MH": 14.5,
}


def warn(fmt_str, *args):
    print(f"{Fore.RED}WARNING: {fmt_str}{Fore.RESET}" % args)


def printgreen(fmt_str, *args):
    print(f"{Fore.GREEN}{fmt_str}{Fore.RESET}" % args)


def raise_err(fmt_str, *args):
    raise RuntimeError(f"{Fore.RED}{fmt_str}{Fore.RESET}" % args)


def get_args():
    """Process command line arguments and configuration file settings.

    This function implements a two-stage argument parsing system that allows arguments
    to be specified either via command line or through a configuration file. The process works as follows:
    Arguments can be provided in two ways:
    1. Command line: python script.py --output out.csv --upop_files data/*.feather
    2. Config file:  python script.py -c config.cfg
       Where config.cfg contains:
       [main]
       output = out.csv
       upop_files = data/*.feather

    Returns:
        argparse.Namespace: Parsed arguments with all values resolved
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", "-o", help="Output file")
    parser.add_argument(
        "--upop_files", "-f", nargs="+", required=True, help="UrbanPop feather files"
    )
    # parser.add_argument(
    #    "--shape_files",
    #    "-e",
    #    nargs="+",
    #    required=True,
    #    default=[],
    #    help="Census block group shape files. Available from\n"
    #    + "https://www.census.gov/cgi-bin/geo/shapefiles/index.php?year=2010&layergroup=Block+Groups",
    # )
    parser.add_argument(
        "--lodes_files",
        "-l",
        nargs="+",
        required=True,
        default=[],
        help="LODES7 origin-destination (OD) files in CSV format. Not needed if UrbanPop nighttime/daytime files are used",
    )
    parser.add_argument(
        "--schools_file",
        "-s",
        required=True,
        default="",
        help="File containing schools data in CSV format. Not needed if UrbanPop nighttime/daytime files are used",
    )
    parser.add_argument(
        "--up_nt_dt_files",
        "-n",
        nargs="+",
        default=[],
        help="Files containing nighttime/daytime data from UrbanPop in feather format. Used instead of LODES files",
    )
    parser.add_argument("--rseed", "-r", default=29, type=int, help="Random seed")

    main_args = {}
    reqd_args = []
    file_lists = []
    for action in parser._actions:
        main_args[action.dest] = action.default
        if action.required:
            reqd_args.append(action.dest)
        if action.nargs == "+":
            file_lists.append(action.dest)

    cfg_parser = argparse.ArgumentParser(
        description="Convert UrbanPop feather files to a csv file for ExaEpi input", add_help=False
    )
    cfg_parser.add_argument("-c", "--config", help="Config file", metavar="FILE")
    args, remaining_argv = cfg_parser.parse_known_args()
    if args.config:
        cfg = configparser.ConfigParser()
        cfg.read([args.config])
        for item in cfg.items("main"):
            if item[0] not in main_args:
                warn(f"{item[0]} not recognized as a valid argument, ignoring it")
        main_args.update(dict(cfg.items("main")))
        for arg in main_args:
            if arg in reqd_args and (main_args[arg] == "" or main_args[arg] == []):
                raise ValueError(
                    f"Required argument {arg} not specified in config file {args.config}"
                )
            if arg in file_lists and main_args[arg] != []:
                main_args[arg] = glob.glob(main_args[arg])

    new_parser = argparse.ArgumentParser(parents=[cfg_parser])
    for action in parser._actions:
        if action.option_strings[0] == "-h":
            continue
        # Only pass non-None strings to add_argument
        add_arg_kwargs = {
            "dest": action.dest,
            "default": main_args[action.dest],
            "nargs": action.nargs,
            "help": action.help,
            "required": (
                True
                if action.required
                and (
                    main_args[action.dest] == ""
                    or main_args[action.dest] == []
                    or main_args[action.dest] is None
                )
                else False
            ),
        }
        if action.type is not None:
            add_arg_kwargs["type"] = action.type
        new_parser.add_argument(
            *[opt for opt in action.option_strings if opt is not None],
            **add_arg_kwargs,
        )
    args = new_parser.parse_args(remaining_argv)
    print(Fore.CYAN, "Options:", sep="")
    for arg, value in args.__dict__.items():
        print(f"  {arg:20s} {value}")
    print(Fore.RESET, end="")
    return args


def dump_intermediate(df, fname, override=False):
    if DUMP_INTERMEDIATES or override:
        print(f"{Fore.CYAN}Dumping intermediate file {fname}.intermediate.csv{Fore.RESET}")
        df.to_csv(fname + ".intermediate.csv", index=False)


@timer
def load_upop_feather_files(fnames, out_fname=""):
    printgreen(f"Reading UrbanPop data from {len(fnames)} files")
    dfs = []
    df = pd.DataFrame()
    chunk_size = int(len(fnames) / 10)
    for i, fname in enumerate(fnames):
        df_read = pd.read_feather(fname, use_threads=True)
        dfs.append(df_read)
        if i == len(fnames) - 1 or i % chunk_size == 0:
            dfs.append(df)
            df = pd.concat(dfs, ignore_index=True)
            del dfs
            dfs = []
            gc.collect()
            mem_used = float(psutil.Process(os.getpid()).memory_info().rss) / 1024 / 1024 / 1024
            mem_of_df = float(df.memory_usage().sum()) / 1024 / 1024 / 1024
            if chunk_size > 0:
                print(f"  {int(i / chunk_size)}:", end="")
            print(f" read {fname}, memory RSS {mem_used:0.2f} G, memory of df {mem_of_df:0.2f} G")

    print(f"Read {len(df.index)} records")
    # need to sort to ensure the order is the same between the population files and the
    # daytime/nighttime files
    df.sort_values(by=["p_id"], inplace=True)
    if out_fname != "":
        dump_intermediate(df, out_fname + ".upop")
    return df


@timer
def set_types(df):
    # treat the NAICS types as strings for later sorting - make them string to convert to a category
    df.pr_naics = df.pr_naics.str.extract(r"(\d+)", expand=False).fillna(-1).astype("string")
    df.h_id = df.h_id.str.split("-").str[-1].astype("int32")

    for field_type in df:
        if field_type in categ_types:
            # compare the list with the unique to make sure we haven't found anything not in our
            # predefined list
            categs_found = list(df[field_type].unique())
            categs_expected = list(categ_types[field_type].categories)
            missing = [
                x
                for x in categs_found
                if x not in categs_expected and x != "" and x != "-1" and x is not None
            ]
            if missing:
                warn(f"Found missing categories for {field_type}: {missing}")
            df[field_type] = df[field_type].astype(categ_types[field_type]).cat.codes
        else:
            if df.dtypes[field_type] == object:
                df[field_type] = df[field_type].astype("string")
            else:
                # this converts all float to int
                max_val = df[field_type].max()
                if max_val < 128:
                    df[field_type] = df[field_type].astype("int8")
                elif max_val < 2**15:
                    df[field_type] = df[field_type].astype("int16")
                elif max_val < 2**31:
                    df[field_type] = df[field_type].astype("int32")
                else:
                    df[field_type] = df[field_type].astype("int64")

    df.pr_naics = df.pr_naics.astype("int16")


def rename_fields(df):
    df.rename(columns={"geoid": "home_geoid", "h_id": "household_id", "p_id": "id"}, inplace=True)
    for col in df.columns:
        if col.startswith("pr_"):
            df.rename(columns={col: col[3:]}, inplace=True)
        elif col.startswith("h_"):
            df.rename(columns={col: "home_" + col[2:]}, inplace=True)
        elif col.startswith("w_"):
            df.rename(columns={col: "work_" + col[2:]}, inplace=True)
        elif col.startswith("hh_"):
            df.rename(columns={col: "household_" + col[3:]}, inplace=True)


def get_level_from_age(min_age, max_age):
    if min_age >= 18:
        return "U"
    if max_age == 3:
        return "C"
    return get_schools.get_level_from_age(min_age, max_age)


@timer
def process_upop_nt_dt(up_nt_dt_files, upop_df):
    printgreen("Loading UrbanPop nighttime/daytime files")
    df = pd.DataFrame()
    # get NAICS from base UrbanPop data - it gives more detailed categories
    for fname in up_nt_dt_files:
        region_df = pd.read_feather(fname)[
            ["p_id", "role", "orig_geoid", "dest_geoid", "school_id", "grade"]
        ].astype({"orig_geoid": "string", "dest_geoid": "string"})
        df = pd.concat([df, region_df], ignore_index=True)
    print(f"Loaded {len(df)} entries from {len(up_nt_dt_files)} files")
    df.sort_values(by=["p_id"], inplace=True)
    # convert the grades to a number (category code)
    idx = df["grade"].isin(
        ["childcare", "undergrad_male", "undergrad_female", "grad_male", "grad_female"]
    )
    df.loc[idx, "grade"] = df.loc[idx, "grade"].str.split("_", n=1, expand=True).iloc[:, 0]
    df.loc[~idx, "grade"] = df.loc[~idx, "grade"].str.split("_", n=1, expand=True).iloc[:, 1]
    df.grade = df.grade.astype(categ_types["pr_grade"]).cat.codes
    df.loc[df.grade != -1, "grade"] += 3  # add 3 to the grade to match UrbanPop data
    df.rename(
        columns={
            "p_id": "id",
            "orig_geoid": "home_geoid",
            "dest_geoid": "work_geoid",
            "grade": "nt_dt_grade",
        },
        inplace=True,
    )

    upop_len = len(upop_df)
    upop_df = upop_df[upop_df["id"].isin(df["id"])].reset_index(drop=True)
    if len(upop_df) != upop_len:
        warn(f"Dropped {upop_len - len(upop_df)} entries not found in daytime/nightime")

    if not np.array_equal(df.id.to_numpy(), upop_df.id.to_numpy()):
        print(f"ids: {df.id.to_numpy()[:10]}\n{upop_df.id.to_numpy()[:10]}")
        raise_err("Mismatched p_ids for population vs daytime/nightime")
    if not np.array_equal(df.home_geoid.to_numpy(), upop_df.home_geoid.to_numpy()):
        print(f"home geoids: {df.home_geoid.to_numpy()[:10]}\n{upop_df.home_geoid.to_numpy()[:10]}")
        raise_err("Mismatched geoids for population vs daytime/nightime")

    df.drop(columns=["home_geoid"], inplace=True)
    df = df.merge(upop_df, on="id", how="outer")

    # dump the mismatched grades
    if not np.array_equal(df.grade.to_numpy(), df.nt_dt_grade.to_numpy()):
        mismatched_df = df[df.grade != df.nt_dt_grade].copy()
        mismatched_df.to_csv("upop_grade_mismatches.csv", index=False)
        print(f"Saved {len(mismatched_df)} mismatched grade rows to upop_grade_mismatches.csv")

    dump_intermediate(df, "upop_with_nt_dt")
    # copy the grades from the upop nt/dt data
    df.grade = df.nt_dt_grade.astype("int8")
    df.loc[(df.role == "worker") | (df.role == "nope"), "grade"] = np.int8(-1)
    df.loc[(df.role == "worker") | (df.role == "nope"), "school_id"] = ""
    df.drop(columns=["nt_dt_grade"], inplace=True)

    workers_df = df[df.role == "worker"].reset_index(drop=True).drop(columns=["role"])
    dump_intermediate(workers_df, "workers_from_upop_nt_dt")
    dump_intermediate(workers_df, "workers_from_upop_nt_dt")

    unemp_df = df[df.role == "nope"].reset_index(drop=True).drop(columns=["role"])
    dump_intermediate(unemp_df, "unemployed_from_upop_nt_dt")

    # students must also have an allocated school_id
    students_without_schools = len(df[(df.role == "student") & (df.school_id == "")])
    if students_without_schools > 0:
        warn(f"Found {students_without_schools} students without school assignments")
    students_df = df[(df.role == "student") & (df.school_id != "")].reset_index(drop=True)
    students_df.drop(columns=["role"], inplace=True)
    students_df.naics = -1
    dump_intermediate(students_df, "students_from_upop_nt_dt")

    schools_df = (
        students_df.groupby(["school_id", "work_geoid"]).size().reset_index(name="students")
    )
    dump_intermediate(schools_df, "schools_from_upop_nt_dt")
    schools_df.rename(columns={"school_id": "id", "work_geoid": "geoid"}, inplace=True)
    schools_df["min_age"] = students_df.groupby(["school_id", "work_geoid"], as_index=False)[
        "grade"
    ].min()["grade"]
    schools_df["max_age"] = students_df.groupby(["school_id", "work_geoid"], as_index=False)[
        "grade"
    ].max()["grade"]
    schools_df["level"] = list(
        map(get_level_from_age, schools_df["min_age"], schools_df["max_age"])
    )

    # set the teachers according to predefined ratios
    schools_df["teachers"] = schools_df["students"].astype("float") / schools_df["level"].map(
        teacher_ratios
    ).round().astype("int32")
    schools_df["teachers"] = schools_df["teachers"].clip(lower=1)  # at least one teacher per school

    schools_df = schools_df[["id", "students", "teachers", "level", "geoid"]]
    dump_intermediate(schools_df, "schools_with_geoids_upop_nt_dt")
    return workers_df, students_df, schools_df, unemp_df


@timer
def process_upop(df, out_fname):
    printgreen("Processing UrbanPop data")
    # only include these fields in the output csv and c++ structure
    include_fields = {
        "p_id",
        # "pums_id",
        "h_id",
        "geoid",
        # "hh_size",
        # "hh_type",
        # "hh_living_arrangement",
        # "hh_age",
        # "hh_has_kids",
        # "hh_income",
        # "hh_nb_wrks",
        # "hh_nb_non_wrks",
        # "hh_nb_adult_wrks",
        # "hh_nb_adult_non_wrks",
        # "hh_dwg",
        # "hh_tenure",
        # "hh_vehicles",
        "pr_age",
        "pr_sex",
        "pr_race",
        # "pr_hsplat",
        # "pr_ipr",
        "pr_naics",
        # "pr_emp_stat",
        "pr_travel",
        "pr_veh_occ",
        # "pr_commute",
        "pr_grade",
    }
    df.drop(columns=set(df.columns.values) - include_fields, inplace=True)
    set_types(df)
    rename_fields(df)
    df.loc[df.grade != -1, "grade"] += 3
    dump_intermediate(df, out_fname + ".upop.purged")


@timer
def get_lodes_groups(lodes_fnames):
    printgreen("Loading LODES files")
    # Origin-Destination (OD) File Structure (LODES flows)
    # Pos Variable Type Explanation
    # 1 w_geocode Char15 Workplace Census Block Code
    # 2 h_geocode Char15 Residence Census Block Code
    # 3 S000 Num Total number of jobs
    # 4 SA01 Num Number of jobs of workers age 29 or younger
    # 5 SA02 Num Number of jobs for workers age 30 to 54
    # 6 SA03 Num Number of jobs for workers age 55 or older
    # 7 SE01 Num Number of jobs with earnings $1250/month or less
    # 8 SE02 Num Number of jobs with earnings $1251/month to $3333/month
    # 9 SE03 Num Number of jobs with earnings greater than $3333/month
    # 10 SI01 Num Number of jobs in Goods Producing industry sectors
    # 11 SI02 Num Number of jobs in Trade, Transportation, and Utilities industry sectors
    # 12 SI03 Num Number of jobs in All Other Services industry sectors
    # 13 createdate Char Date on which data was created, formatted as YYYYMMDD
    df = pd.DataFrame()
    for lodes_fname in lodes_fnames:
        print("Loading", lodes_fname)
        lodes_df = pd.read_csv(
            lodes_fname, dtype={"w_geocode": str, "h_geocode": str, "S000": int}
        )[["w_geocode", "h_geocode", "S000"]]
        # print("Loaded", len(lodes_df), "entries")
        # truncate geoids to first 12, i.e. just census block groups
        lodes_df.h_geocode = lodes_df.h_geocode.str[:12]
        lodes_df.w_geocode = lodes_df.w_geocode.str[:12]
        lodes_df = (
            lodes_df.groupby(["w_geocode", "h_geocode"])
            .S000.sum()
            .reset_index()
            .rename(columns={0: "count"})
        )
        dump_intermediate(lodes_df, lodes_fname + "_short")
        df = pd.concat([df, lodes_df], ignore_index=True)
    return df


@timer
def set_childcare(upop_df):
    printgreen("Setting childcare")
    # UrbanPop doesn't have allocations to childcare outside of PK in schools, so we randomly
    # assign agents under age 5 not in PK to childcare. According to NCES, 32% of under 1 year,
    # 47% of 1-2 yrs and 83 of 3-5 yrs are in center-based care
    PROBS = {0: 0.32, 1: 0.47, 2: 0.47, 3: 0.83, 4: 0.83}
    df = upop_df.copy()
    for age in np.arange(0, 5):
        is_candidate = (df.grade == -1) & (df.age == age)
        num_candidates = int(len(df[is_candidate]) * PROBS[age])  # type: ignore
        to_set = df[is_candidate].sample(n=num_candidates, replace=False)
        print("  Age", age, "set", len(to_set), "out of", len(df[is_candidate]))
        df.loc[to_set.index, "grade"] = 3

    print("Set", len(df[df.grade == 3]), "agents to childcare")
    dump_intermediate(df, "childcare")
    return df


@timer
def load_schools(fname):
    printgreen(f"Loading schools from {fname}")
    schools_df = pd.read_csv(fname, low_memory=False, dtype={"geoid": str})
    print(
        f"Loaded {len(schools_df)} entries: {schools_df.students.sum()} students, "
        f"{schools_df.teachers.sum()} teachers"
    )
    dump_intermediate(schools_df, "schools")
    return schools_df


@timer
def alloc_workers(lodes_df, workers_df):
    printgreen("Allocating workers")
    worker_groups = workers_df.groupby(["home_geoid"])
    # only use the lodes groups where both the home and work geoids are found in the workers home
    # geoid
    worker_geoids = set(worker_groups.groups.keys())
    lodes_groups = lodes_df[
        lodes_df.w_geocode.isin(worker_geoids) & lodes_df.h_geocode.isin(worker_geoids)
    ].groupby(["h_geocode"])
    df = pd.DataFrame()
    print(f"Assigning workers in {len(worker_groups)} GEOIDS for {len(lodes_groups)} LODES groups")
    i = 0
    nt_dts = [df]
    for name, worker_group in worker_groups:
        i += 1
        if i % 100 == 0:
            print(f"  {i} {name[0]}")
        num_workers = len(worker_group)
        try:
            lodes_group = lodes_groups.get_group(name)
        except KeyError as err:
            # the home geoid derived from the upop workers is not found in the home (origin) geoid
            # in the LODES data, so we haveno flows from that geoid
            warn(f"Could not find origin GEOID {name} in LODES data for {num_workers} workers")
            lodes_group = pd.DataFrame()
            lodes_group["w_geocode"] = name
            lodes_group["h_geocode"] = name
            lodes_group["S000"] = num_workers
            # raise err
        sum_flows = lodes_group["S000"].sum()
        flow_probs = lodes_group["S000"] / sum_flows
        rnd_sample = lodes_group.sample(n=num_workers, weights=flow_probs, replace=True)
        # nt_dt_group = worker_group[["id", "home_geoid", "naics", "grade"]]
        worker_group = worker_group.assign(dest_geoid=rnd_sample["w_geocode"].tolist())
        nt_dts.append(worker_group)

    df = pd.concat(nt_dts, ignore_index=True)
    df.rename(columns={"dest_geoid": "work_geoid"}, inplace=True)
    # workers have no grade since that indicates that the agent is in school
    df["grade"] = np.int8(-1)
    df["school_id"] = ""
    num_without_naics = len(df.loc[df["naics"] == -1, "naics"])
    if num_without_naics > 0:
        warn(f"There are {num_without_naics} workers without NAICS classification")
    print("Added destinations for", len(df), "workers")
    dump_intermediate(df, "workers_nt_dt")

    return df


# @timer
def alloc_students_region(students_df, schools_df, geoid_scaling, alloc_all):
    schools_df["region"] = schools_df.geoid.str[:geoid_scaling]
    dump_intermediate(schools_df, "schools_" + region_scales[geoid_scaling])
    students_df["region"] = students_df.home_geoid.str[:geoid_scaling]
    dump_intermediate(students_df, "students_" + region_scales[geoid_scaling])
    student_groups = students_df.groupby(["region"])
    school_groups = schools_df.groupby(["region"])

    def process_region(args):
        region, student_group = args
        num_students_reqd = len(student_group)
        if num_students_reqd == 0:
            warn(f"No students requested for group {region}")
            return None
        try:
            school_group = school_groups.get_group(region)
        except KeyError:
            return None
        school_group = school_group[["geoid", "id", "remaining_student_places"]]
        sum_remaining_student_places = school_group.remaining_student_places.sum()
        if not alloc_all and num_students_reqd > sum_remaining_student_places:
            # add an extra dummy row so that all students have a chance of being allocated to
            # available slots
            school_group.loc[len(school_group)] = [
                "",
                "",
                num_students_reqd - sum_remaining_student_places,
            ]
            sum_remaining_student_places = school_group.remaining_student_places.sum()

        school_probs = school_group.remaining_student_places / sum_remaining_student_places
        schools_selected = school_group.sample(
            n=num_students_reqd, weights=school_probs, replace=True
        )
        geoids = schools_selected.geoid.values
        school_ids = schools_selected.id.values
        # clear out dummy schools
        schools_selected.index.rename("index", inplace=True)
        schools_selected = schools_selected[(schools_selected.id != "")]
        if len(schools_selected) == 0:
            return None
        counts = schools_selected.groupby("index").size()
        return {
            "student_idx": student_group.index,
            "work_geoids": geoids,
            "school_ids": school_ids,
            "school_counts": counts,
        }

    with ThreadPool(processes=2) as pool:
        results = pool.map(process_region, [(region, group) for region, group in student_groups])

    for result in results:
        if result is None:
            continue
        students_df.loc[result["student_idx"], "work_geoid"] = result["work_geoids"]
        students_df.loc[result["student_idx"], "school_id"] = result["school_ids"]
        schools_df.loc[result["school_counts"].index, "remaining_student_places"] -= result[
            "school_counts"
        ].values
        schools_df.remaining_student_places = schools_df.remaining_student_places.clip(lower=1)

    print(
        f"  For {region_scales[geoid_scaling]}, allocated "
        f"{len(students_df[students_df.school_id != ''])} students"
        f" out of {len(students_df)}"
    )

    students_df.drop(columns=["region"], inplace=True)
    return students_df


@timer
def alloc_students_level(schools_df, students_df, level):
    ids_before = students_df.id.to_numpy()
    print(f"Allocating {len(students_df)} students for level {level}")
    dump_intermediate(students_df[["id", "grade"]], "students-" + level)
    # Get all schools with the required level
    schools_df = schools_df[(schools_df.level.str.find(level) != -1)].copy()
    # Some schools have multiple levels and so students should be allocated proportionately. For
    # simplicity, we just allocate uniformly among the levels, e.g. a EMH school would have 1/3
    # students each in elem, middle and high
    schools_df.loc[:, "students"] = np.int32(
        np.ceil(schools_df.students / schools_df.level.str.len())
    )
    schools_df["remaining_student_places"] = schools_df.students
    # for childcare, we assume that it is all close to home
    scales = list(region_scales.keys()) if level != "C" else list(region_scales.keys())[:3]
    # pick schools for students from decreasing resolution; the goal is to allocate students as
    # close to home as possible
    for scale in scales:
        # make sure to allocate all at the final region scale
        alloc_all = True if scale == scales[-1] else False
        unassigned_df = students_df[(students_df.school_id == "")].copy()
        assigned_df = alloc_students_region(unassigned_df, schools_df, scale, alloc_all)
        students_df.loc[assigned_df.index, "school_id"] = assigned_df.school_id.astype("string")
        students_df.loc[assigned_df.index, "work_geoid"] = assigned_df.work_geoid
        num_unalloc = len(students_df[(students_df.school_id == "")])
        if num_unalloc == 0:
            break

    num_unalloc = len(students_df[(students_df.school_id == "")])
    if num_unalloc > 0:
        students_df.loc[students_df.school_id == "", "work_geoid"] = students_df.home_geoid
        students_df.loc[students_df.school_id == "", "grade"] = -1

    ids_after = students_df.id.to_numpy()
    if not np.array_equal(ids_before, ids_after):
        raise_err(f"mismatched ids: {len(ids_before)} != {len(ids_after)}")

    return students_df


def process_level(level, schools, students):
    level_students = students[
        (students.grade >= age_levels[level][0]) & (students.grade <= age_levels[level][1])
    ].copy()
    if len(level_students) == 0:
        return pd.DataFrame()
    return alloc_students_level(schools, level_students, level)


@timer
def alloc_students(schools_df, students_df):
    printgreen("Allocating students")
    num_unique_before = len(students_df.id.unique())
    students_df["school_id"] = ""
    students_df["naics"] = -1
    students_df["work_geoid"] = students_df.home_geoid

    USE_MULTIPROCS = True
    dfs = []
    # allocate students from each level
    if not USE_MULTIPROCS:
        for level in ["P", "E", "M", "H", "U", "C"]:
            level_students_df = students_df[
                (students_df.grade >= age_levels[level][0])
                & (students_df.grade <= age_levels[level][1])
            ].copy()
            if len(level_students_df) == 0:
                continue
            df = alloc_students_level(schools_df, level_students_df, level=level)
            dfs.append(df)

    elif USE_MULTIPROCS:
        levels = ["P", "E", "M", "H", "U", "C"]
        with Pool(processes=6) as pool:
            process_level_partial = partial(process_level, schools=schools_df, students=students_df)
            dfs = pool.map(process_level_partial, levels)

    students_df = pd.concat(dfs, ignore_index=True)

    num_unique_after = len(students_df.id.unique())
    if num_unique_before != num_unique_after:
        warn(f"mismatched unique ids: {num_unique_before} != {num_unique_after}")
    # set all unallocated students
    unalloc = students_df.school_id == ""
    if len(students_df.loc[unalloc]) > 0:
        warn(f"Found {len(students_df.loc[unalloc])} unallocated students")
        students_df.loc[unalloc, "work_geoid"] = students_df.home_geoid
        students_df.loc[unalloc, "grade"] = -1

    dump_intermediate(students_df, "students_nt_dt")

    return students_df


def check_school_id_correlation(students_df, schools_df, description):
    # now check correlation of generated data with actual schools data, for each named school size
    gen_schools_df = students_df.groupby(["school_id"]).size().reset_index(name="students")
    gen_schools_df["key"] = gen_schools_df["school_id"].astype(str)

    schools_check_df = schools_df.copy()
    schools_check_df["key"] = schools_check_df["id"].astype(str)
    # only merge in the matching schools from the actual data, since that consists of potentially
    # many more schools than we are using for this subset (e.g. if we are doing a single state)
    merged_df = gen_schools_df.merge(
        schools_check_df, on="key", how="left", suffixes=["_gen", "_orig"]
    )[["key", "students_gen", "students_orig"]]
    merged_df = merged_df.fillna(0).astype({"students_gen": "int", "students_orig": "int"})
    dump_intermediate(merged_df, "schools_check_name")
    corr = merged_df.students_gen.corr(merged_df.students_orig)
    print(
        f"{description} school ID correlation: {corr:.3f} "
        + f"(generated count {merged_df.students_gen.sum()}, "
        f"actual count {merged_df.students_orig.sum()})"
    )
    if corr < CORR_CHECK_LEVEL:
        warn("Low correlation!")


def check_school_geoid_correlation(students_df, schools_df, description):
    # now check correlation for location (geoid)
    gen_schools_df = students_df.groupby(["work_geoid"]).size().reset_index(name="count")
    gen_schools_df["key"] = gen_schools_df["work_geoid"].astype(str)

    schools_check_df = schools_df.groupby(["geoid"]).students.sum().reset_index(name="count")
    schools_check_df["key"] = schools_check_df["geoid"].astype(str)
    # only merge in the matching schools from the actual data, since that consists of potentially
    # many more schools than we are using for this subset (e.g. if we are doing a single state)
    merged_df = gen_schools_df.merge(
        schools_check_df, on="key", how="left", suffixes=["_gen", "_orig"]
    )[["key", "count_gen", "count_orig"]]
    merged_df = merged_df.fillna(0).astype({"count_gen": "int", "count_orig": "int"})
    dump_intermediate(merged_df, "schools_check_geoid")
    corr = merged_df.count_gen.corr(merged_df.count_orig)
    print(
        f"{description} school geoid correlation: {corr:.3f} "
        + f"(generated count {merged_df.count_gen.sum()}, "
        f"actual count {merged_df.count_orig.sum()})"
    )
    if corr < CORR_CHECK_LEVEL:
        warn("Low correlation!")


def print_school_counts(students_df, workers_df):
    print("School counts (educators, students, ratio):")
    level_names = {
        "C": "Childcare",
        "PE": "Elementary",
        "M": "Middle",
        "H": "High",
        "U": "College",
    }
    tot_students = 0
    tot_teachers = 0
    for level in ["U", "H", "M", "PE", "C"]:
        num_students = len(
            students_df[
                (students_df.grade >= age_levels[level][0])
                & (students_df.grade <= age_levels[level][1])
            ]
        )
        tot_students += num_students
        num_teachers = len(
            workers_df[
                (workers_df.grade >= age_levels[level][0])
                & (workers_df.grade <= age_levels[level][1])
            ]
        )
        print(
            f"  {level_names[level]:10s} {num_teachers} {num_students} "
            f"{num_students / num_teachers:.1f}"
        )
        tot_teachers += num_teachers
    print(f"  Total     {tot_teachers} {tot_students} {tot_students / tot_teachers:.1f}")


@timer
def generate_nt_dt(schools_df, upop_df, lodes_df):
    # randomly allocate some young agents to childcare
    upop_df = set_childcare(upop_df)

    num_unique_ids = len(upop_df.id.unique())

    # now split into students, workers and unemployed.
    # Note that the UrbanPop nt/dt data classifies mil as unemployed (nope); because they don't
    # commute?
    # UrbanPop nt/dt sometimes classifies employed people with assigned grades as students, not
    # workers. Not sure when/why it does this. We will assume that employed agents with assigned
    # grades are students if they are under 25 in age. We determine who is employed by checking who
    # has a NAICS code
    # is_employed = (upop_df.pr_emp_stat == "employed") & (
    #    (upop_df.pr_grade == "") | (upop_df.pr_age >= 25)
    # )
    is_employed = (upop_df.naics != -1) & ((upop_df.grade == -1) | (upop_df.age > 26))
    in_school = (upop_df.grade != -1) & ~is_employed
    students_df = upop_df[in_school].copy()
    workers_df = upop_df[is_employed]
    unemp_df = upop_df[~is_employed & ~in_school].copy()
    tot = len(workers_df) + len(students_df) + len(unemp_df)
    print("Counts:")
    print("  workers:   ", len(workers_df))
    print("  students:  ", len(students_df))
    print("  unemployed:", len(unemp_df))
    print("  total:     ", tot)
    if tot != len(upop_df):
        print(
            "ERROR: total agents mismatch, allocated",
            tot,
            "but found",
            len(upop_df),
            "in UrbanPop feather files",
        )

    workers_nt_dt_df = alloc_workers(lodes_df, workers_df)

    df = pd.concat([workers_nt_dt_df, students_df, unemp_df], ignore_index=True)
    if num_unique_ids != len(df.id.unique()):
        raise_err(f"Incorrect number of unique IDS {len(df.id.unique())}")

    students_nt_dt_df = alloc_students(schools_df, students_df)

    df = pd.concat([workers_nt_dt_df, students_nt_dt_df, unemp_df], ignore_index=True)
    if num_unique_ids != len(df.id.unique()):
        print(len(students_df), len(students_nt_dt_df))
        raise_err(f"Incorrect number of unique IDS {len(df.id.unique())}")

    unemp_df["work_geoid"] = unemp_df.home_geoid
    unemp_df.school_id = ""
    unemp_df.grade = np.int8(-1)
    unemp_df.naics = np.int16(-1)

    return workers_nt_dt_df, students_nt_dt_df, schools_df, unemp_df


def alloc_teachers_region(teachers_df, schools_df, geoid_scaling):
    schools_df["region"] = schools_df.geoid.str[:geoid_scaling]
    teachers_df["region"] = teachers_df.work_geoid.str[:geoid_scaling]
    teacher_groups = teachers_df.groupby(["region"])
    school_groups = schools_df.groupby(["region"])
    missing_regions = 0
    tot_reqd_teachers = 0
    for group_name, school_group in school_groups:
        num_teachers_reqd = school_group.adj_teachers.sum()
        # print(f"group name {group_name} num_teachers_reqd {num_teachers_reqd}")
        if num_teachers_reqd == 0:
            continue
        tot_reqd_teachers += num_teachers_reqd
        try:
            teacher_group = teacher_groups.get_group(group_name)
        except KeyError:
            missing_regions += 1
            continue
        num_teachers_reqd = min(num_teachers_reqd, teacher_group.id.count())
        teachers_selected = teacher_group.sample(n=num_teachers_reqd, replace=False)
        probs = school_group.adj_teachers / num_teachers_reqd
        schools_selected = school_group.sample(n=num_teachers_reqd, weights=probs, replace=True)
        schools_selected.index.rename("index", inplace=True)
        schools_selected["grade"] = (
            schools_selected["level"]
            .map(age_levels)
            .apply(lambda x: np.random.randint(x[0], x[1] + 1))
            .astype("int8")
        )
        # the university teachers will be uniformly split betw undergrad and grad. Readjust this to
        # a 80:20 split
        # FIXME: at college level, "teachers" will likely interact with both grad and undergrads
        schools_selected["rnd"] = np.random.uniform(size=len(schools_selected))
        schools_selected.loc[
            (schools_selected.grade == 19) & (schools_selected.rnd < 0.5), "grade"
        ] = 18
        schools_selected.grade = schools_selected.grade.astype("int8")
        schools_selected.id = schools_selected.id.astype("string")
        teachers_df.loc[teachers_selected.index, "school_id"] = list(schools_selected.id)
        teachers_df.loc[teachers_selected.index, "grade"] = np.array(
            list(schools_selected.grade), dtype=np.int8
        )
        teachers_df.loc[teachers_selected.index, "work_geoid"] = list(schools_selected.geoid)
        # reduce the reqd teachers count according to how many have been allocated
        schools_selected_groups = schools_selected.groupby(["index"])
        selected_school_indexes = list(schools_selected_groups.groups.keys())
        selected_school_counts = schools_selected_groups.id.count().tolist()
        schools_df.loc[schools_df.index.isin(selected_school_indexes), "adj_teachers"] -= np.int32(
            selected_school_counts
        )
        schools_df.loc[schools_df.adj_teachers < 0, "adj_teachers"] = 0
        schools_df.loc[
            schools_df.index.isin(selected_school_indexes), "alloc_teachers"
        ] -= np.int32(selected_school_counts)

    teachers_df.drop("region", axis=1, inplace=True)
    num_allocated = len(teachers_df[(teachers_df.grade != -1)])
    print(
        f"  For {region_scales[geoid_scaling]}, allocated {num_allocated} teachers"
        f" out of {tot_reqd_teachers}"
    )
    return teachers_df


@timer
def alloc_teachers_for_school_type(workers_df, students_df, schools_df, school_type):
    printgreen(f"Allocating teachers for {school_type}")
    # The number of students at each school will not exactly match the original schools data, so we
    # use the actual number of students we have allocated, and the original student/teacher ratio
    # to set the desired teacher counts for each school
    if school_type == "childcare":
        naics_code = categ_types["pr_naics"].categories.get_loc("6244")
        schools_df = schools_df[schools_df.level == "C"]
        students_df = students_df[students_df.grade <= 3]
    elif school_type == "secondary":
        naics_code = categ_types["pr_naics"].categories.get_loc("6111")
        schools_df = schools_df[
            (schools_df.level == "E")
            | (schools_df.level == "EM")
            | (schools_df.level == "EMH")
            | (schools_df.level == "M")
            | (schools_df.level == "MH")
            | (schools_df.level == "H")
            | (schools_df.level == "P")
            | (schools_df.level == "PE")
            | (schools_df.level == "PEM")
            | (schools_df.level == "PEMH")
        ]
        students_df = students_df[(students_df.grade > 3) & (students_df.grade <= 17)]
    elif school_type == "university":
        naics_code = categ_types["pr_naics"].categories.get_loc("611")
        schools_df = schools_df[schools_df.level == "U"]
        students_df = students_df[(students_df.grade >= 18) & (students_df.grade <= 19)]
    else:
        raise_err(f"School_type {school_type} not valid")

    print(f"Number of schools to use {len(schools_df)}, number of students {len(students_df)}")

    alloc_schools_df = students_df.groupby(["school_id"])["id"].count().reset_index()
    alloc_schools_df = alloc_schools_df.rename(columns={"id": "alloc_students", "school_id": "id"})

    schools_df = schools_df.merge(alloc_schools_df, on="id")
    schools_df["ratio"] = schools_df.alloc_students / schools_df.students
    schools_df["adj_teachers"] = np.int32(np.ceil(schools_df.teachers * schools_df.ratio))

    dump_intermediate(schools_df, "schools_" + school_type)
    schools_df["alloc_teachers"] = schools_df.adj_teachers
    teachers_df = workers_df[workers_df.naics == naics_code].copy()  # type: ignore
    num_reqd_teachers = schools_df.adj_teachers.sum()
    print(
        f"Found {len(teachers_df)} workers with NAICS code {naics_code} for "  # type: ignore
        f"{num_reqd_teachers} required teachers, ratio {len(students_df) / num_reqd_teachers:.2f}"
    )
    scales = list(region_scales.keys())
    teachers_df["school_id"] = ""  # pd.Series([""] * len(teachers_df), dtype="string")
    teachers_df["grade"] = np.int8(-1)
    # pick schools for teachers from decreasing resolution; the goal is to allocate teachers as
    # close to home as possible
    for scale in scales:
        avail_teachers = teachers_df[teachers_df.grade == -1].copy()
        teachers_df = alloc_teachers_region(avail_teachers, schools_df, scale)
        assigned_df = teachers_df[teachers_df.grade != -1]
        dump_intermediate(assigned_df, "teachers_" + school_type + "_" + str(region_scales[scale]))
        workers_df.loc[assigned_df.index, "school_id"] = assigned_df.school_id.astype("string")
        workers_df.loc[assigned_df.index, "work_geoid"] = assigned_df.work_geoid
        workers_df.loc[assigned_df.index, "grade"] = assigned_df.grade.astype("int8")
    num_alloced = len(workers_df[(workers_df.grade != -1)])
    if (num_reqd_teachers - num_alloced) > 0:
        warn(f"Failed to allocate {num_reqd_teachers - num_alloced} teachers")

    return workers_df


@timer
def allocate_teachers(workers_df, students_df, schools_df):
    # Filter schools to only include those in worker home geoids
    worker_geoids = set(workers_df.home_geoid.unique())
    schools_filtered = len(schools_df)
    schools_df = schools_df[schools_df.geoid.isin(worker_geoids)]
    if len(schools_df) != schools_filtered:
        print(
            f"Filtered out {schools_filtered - len(schools_df)} "
            f"schools not in worker home geoids"
        )

    for school_type in ["childcare", "secondary", "university"]:
        workers_df = alloc_teachers_for_school_type(
            workers_df, students_df, schools_df, school_type
        )


def adjust_indexes(df, output):
    orig_ids_df = pd.DataFrame()
    df.sort_values(by=["id"], inplace=True)
    orig_ids_df["orig_id"] = df.id
    # make sure all the ids are globally unique and just integers
    df.id = np.arange(0, len(df.index))
    orig_ids_df["new_id"] = df.id
    orig_ids_df.to_csv(output + ".idmap.csv", index=False)

    # convert school ids to unique 64 bit ints
    df.loc[df.school_id == None, "school_id"] = ""
    df.school_id = df.school_id.astype(str)
    df.loc[df.school_id == "nan", "school_id"] = ""
    unique_school_ids = sorted(df.school_id.unique())
    school_id_map = dict(zip(unique_school_ids, range(len(unique_school_ids))))
    school_id_map[""] = 0
    print(f"Found {len(school_id_map)} unique school ids")
    df.school_id = df.school_id.map(school_id_map).astype("int64")
    # save the current 0 values
    zero_idx = df.school_id == 0
    # set school ids to be unique only to work geoid
    df.school_id = df.groupby(["work_geoid"])["school_id"].transform(lambda x: pd.factorize(x)[0])
    # do this to ensure that no valid school remains at 0
    df.school_id += 1
    # reset the non-school rows
    df.loc[zero_idx, "school_id"] = 0
    df.school_id = df.school_id.astype("int16")

    # set household ids to be unique only to home geoid
    df.household_id = (
        df.groupby(["home_geoid"])["household_id"]
        .transform(lambda x: pd.factorize(x)[0])
        .astype("int16")
    )


def check_flows_correlation(df, lodes_df):
    # check that the actual allocated workers follow the lodes flows closely
    generated_df = df.groupby(["home_geoid", "work_geoid"]).size().reset_index(name="total")
    generated_df["key"] = (
        generated_df["home_geoid"].astype(str) + "-" + generated_df["work_geoid"].astype(str)
    )
    lodes_df["key"] = lodes_df["h_geocode"].astype(str) + "-" + lodes_df["w_geocode"].astype(str)
    merged_df = generated_df.merge(lodes_df, on="key", how="outer")[["key", "total", "S000"]]
    merged_df = merged_df.fillna(0).astype({"total": "int", "S000": "int"})
    dump_intermediate(merged_df, "worker_check_ods.csv")
    corr = merged_df.total.corr(merged_df.S000)
    print(
        f"LODES flows correlation: {corr:.3f} (generated count {merged_df.total.sum()}, "
        f"actual count {merged_df.S000.sum()})"
    )
    if corr < CORR_CHECK_LEVEL:
        warn(f"Low correlation")


def print_cpp_header(df):
    hdr_fname = "UrbanPopAgentStruct.H"
    print("Writing C++ header file at", hdr_fname)

    hdr = f"""
/*! @file {hdr_fname}
    \\brief Contains #UrbanPopAgent class used for reading in UrbanPop data
    File automatically generated by UrbanPop-scripts/extract_urbanpop_feather.py
*/

#pragma once

#include <stdlib.h>
#include <string.h>
#include <fstream>
#include <sstream>

using std::string;
using float32_t = amrex::ParticleReal;

namespace UrbanPop {{

const size_t NUM_COLS = {len(df.columns)};

"""
    # """

    # print out string arrays with category names
    for field_type in df:
        categs_expected = None
        if field_type in categ_types:
            categs_expected = list(categ_types[field_type].categories)
        elif "pr_" + field_type in categ_types:
            categs_expected = list(categ_types["pr_" + field_type].categories)
        if categs_expected:
            enum_categs_expected = ["_" + categ for categ in categs_expected]
            num_categs = len(categs_expected)
            hdr += f"""
const int {field_type.upper()}_COUNT = {num_categs};
static string {field_type}_descriptions[{field_type.upper()}_COUNT] = {{"{'", "'.join(categs_expected)}"}};
struct {field_type.upper()} {{ enum {{{', '.join(enum_categs_expected)}}}; }};

"""

    hdr += f"""
static std::vector<string> splitString(const string &s, char delim) {{
    std::vector<string> elems;
    std::stringstream ss(s);
    string item;
    while (std::getline(ss, item, delim)) elems.push_back(item);
    return elems;
}}

"""

    hdr += f"struct UrbanPopAgent {{\n"
    for i, col in enumerate(df.columns):
        hdr += f"    {df.dtypes.iloc[i]}_t {col};\n"

    hdr += """
    bool readCsv(std::ifstream &f) {
        string buf;
        if (!getline(f, buf)) return false;
        if (buf[0] != '*') {
            id = -1;
            return true;
        }
        try {
            std::vector<string> tokens = splitString(buf.substr(2), ',');
            if (tokens.size() != NUM_COLS)
                throw std::runtime_error("Incorrect number of tokens, expected " +
                                          std::to_string(NUM_COLS) +
                                         " got " + std::to_string(tokens.size()));\n"""

    for i, col in enumerate(df.columns):
        if df.dtypes.iloc[i] == "float32":
            hdr += f"            {col} = stof(tokens[{i}]);\n"
        elif df.dtypes.iloc[i] == "int64":
            hdr += f"            {col} = stol(tokens[{i}]);\n"
        elif df.dtypes.iloc[i] == "string":
            hdr += f"            {col} = tokens[{i});\n"
        else:
            hdr += f"            {col} = stoi(tokens[{i}]);\n"
    hdr += f"""
        }} catch (const std::exception &ex) {{
            std::ostringstream os;
            os << "<" << __LINE__ << ">: Error reading UrbanPop input file: " << ex.what()
               << ", line read: " << "'" << buf << "'";
            amrex::Abort(os.str());
        }}
        return true;
    }}\n"""

    hdr += "\n    bool readBinary(std::ifstream &f) {\n"
    for i, col in enumerate(df.columns):
        hdr += f"        if (!f.read(reinterpret_cast<char*>(&{col}), sizeof({df.dtypes.iloc[i]}))) return false;\n"
    hdr += "        return true;\n    }\n"

    hdr += f"""
    friend std::ostream& operator<<(std::ostream& os, const UrbanPopAgent& agent) {{
        os << std::fixed << std::setprecision(6);\n"""

    for i, col in enumerate(df.columns):
        agent = f"agent.{col}"
        if str(df.dtypes.iloc[i]) == "int8":
            hdr += f"        os << (int){agent}"
        else:
            hdr += f"        os << {agent}"
        if col in categ_types or "pr_" + col in categ_types:
            hdr += f""" << ({agent} != -1 ? ":" + {col}_descriptions[{agent}] : "")"""

        if i < len(df.columns) - 1:
            hdr += """ << ",";\n"""
        else:
            hdr += ";\n"

    hdr += """
        return os;
    }
};
} // namespace UrbanPop
"""

    f_hdr = open(hdr_fname, "w")
    print(hdr, file=f_hdr)
    f_hdr.close()
    print("Wrote", len(df.columns), "fields to", hdr_fname)


@timer
def print_agents_csv(df, out_fname):
    num_rows = len(df.index)
    # start with a distinct marker so that the file can be read in parallel more easily
    df.index = ["*"] * num_rows
    # print each geoid in turn so we can track the file offsets
    buff = io.StringIO()
    foffsets = []
    home_pops = []
    home_geoids = []

    num_geoids = df.home_geoid.unique()
    step = int(len(num_geoids) / 10)
    out_fname_csv = out_fname + ".csv"
    printgreen(f"Writing CSV text data to {out_fname_csv}")
    for i, (geoid, subset_df) in enumerate(df.groupby("home_geoid")):
        home_geoids.append(geoid)
        if i % step == 0:
            print(f"  GEOID {geoid} {i}", flush=True)
        foffsets.append(buff.tell())
        home_pops.append(len(subset_df))
        subset_df.to_csv(buff, index=True, header=(i == 0))
    out_fname_csv = out_fname + ".csv"
    with open(out_fname_csv, "w") as f:
        print(buff.getvalue(), end="", file=f)
        print(f"Wrote {len(df)} records in {buff.tell()} bytes")
    buff.close()

    return foffsets, home_pops, home_geoids


@timer
def print_agents_bin(df, out_fname):
    num_rows = len(df.index)
    # start with a distinct marker so that the file can be read in parallel more easily
    df.index = ["*"] * num_rows
    # print each geoid in turn so we can track the file offsets
    # buff = io.StringIO()
    foffsets = []
    home_pops = []
    home_geoids = []
    grouped = df.groupby("home_geoid")
    num_geoids = len(grouped)
    step = max(1, num_geoids // 10)
    out_fname_bin = out_fname + ".bin"
    printgreen(f"Writing binary data to {out_fname_bin}")

    # Build struct format for entire row
    struct_formats = {
        "int64": "q",
        "int32": "i",
        "int16": "h",
        "int8": "b",
        "float32": "f",
        "float64": "d",
    }

    row_format = "".join(struct_formats[str(dt)] for dt in df.dtypes)
    row_struct = struct.Struct(row_format)

    with open(out_fname_bin, "wb") as f:
        for i, (geoid, subset_df) in enumerate(grouped):
            if i % step == 0:
                print(f"  GEOID {geoid} {i}/{num_geoids}", flush=True)

            home_geoids.append(geoid)
            foffsets.append(f.tell())
            home_pops.append(len(subset_df))

            # Convert entire subset to bytes at once
            data_array = subset_df.to_numpy()
            for row in data_array:
                f.write(row_struct.pack(*row))

        file_size = f.tell()
        print(f"Wrote {num_rows} records in {file_size:,} bytes")

    return foffsets, home_pops, home_geoids


@timer
def compute_worker_populations(df):
    class Fake(object):
        def __init__(self, list_obj):
            self.obj = list_obj

    # compute worker populations for each NAICS code
    work_geoids = df.work_geoid.unique()
    naics_types = list(range(len(categ_types["pr_naics"].categories)))
    print(f"Found {len(work_geoids)} unique work GEOIDS and {len(naics_types)} unique NAICS codes")
    work_geoids_df = (
        df.loc[df.naics != -1]
        .groupby(["work_geoid", "naics"])["naics"]
        .count()
        .reset_index(name="num")
    )
    # ensure every GEOID has entries for all the NAICS codes, even ones for count 0
    full_naics_df = pd.DataFrame()
    full_naics_df["work_geoid"] = work_geoids
    full_naics_df["naics"] = Fake(naics_types)
    full_naics_df["num"] = 0
    full_naics_df.naics = full_naics_df.naics.apply(lambda x: x.obj)
    full_naics_df = full_naics_df.explode("naics")
    work_geoids_pops_df = work_geoids_df.merge(
        full_naics_df, on=["work_geoid", "naics"], how="outer"
    ).rename(columns={"num_x": "num"})
    work_geoids_pops_df.drop(columns="num_y", inplace=True)
    work_geoids_pops_df["num"] = work_geoids_pops_df["num"].fillna(0).astype("int")
    return work_geoids_pops_df, naics_types


@timer
def print_index(df, out_fname, foffsets, home_pops, home_geoids):
    work_geoids_pops_df, naics_types = compute_worker_populations(df)
    dump_intermediate(work_geoids_pops_df, out_fname + "_work_geoids_pops")
    work_geoids = df.work_geoid.unique()
    step = int(len(work_geoids) / 10)
    out_fname_idx = out_fname + ".idx"
    printgreen(f"Writing block group indexes to {out_fname_idx}")
    with open(out_fname_idx, mode="w") as f:
        naics_descrs = list(categ_types["pr_naics"].categories)
        print("geoid foff h_pop w_pop", " ".join(naics_descrs), file=f)
        # print work-only GEOIDs
        if len(work_geoids) > len(home_geoids):
            only_work_geoids = list(set(work_geoids) - set(home_geoids))
            warn(f"Found {len(only_work_geoids)} work-only geoids out of {len(work_geoids)}")
            for geoid in only_work_geoids:
                work_pops = work_geoids_pops_df.loc[
                    work_geoids_pops_df.work_geoid == geoid
                ].num.to_list()
                tot_work_pop = np.sum(work_pops)
                print(geoid, 0, 0, tot_work_pop, " ".join(map(str, work_pops)), file=f)
        for i, geoid in enumerate(home_geoids):
            if i % step == 0:
                print(f"  GEOID {geoid} {i}", flush=True)
            work_pops = work_geoids_pops_df.loc[
                work_geoids_pops_df.work_geoid == geoid
            ].num.to_list()
            tot_work_pop = np.sum(work_pops)
            if tot_work_pop == 0:
                work_pops = [0] * len(naics_types)
            if len(work_pops) != len(naics_types):
                print(f"len work_pops {len(work_pops)} != len naics_types {len(naics_types)}")
                print(f"len naics_descrs {len(naics_descrs)}")
                for i, p in enumerate(work_pops):
                    if p > 0:
                        print(i, p, naics_descrs[i])
                print("")
                print(f"Total work pop: {sum(work_pops)}")
                raise_err(
                    f"For geoid {geoid}, work pops != NAICS types, "
                    f"{len(work_pops)} != {len(naics_types)}"
                )

            print(
                geoid,
                foffsets[i],
                home_pops[i],
                tot_work_pop,
                " ".join(map(str, work_pops)),
                file=f,
            )


def sanity_checks(df):
    students_df = df[(df.grade != -1) & (df.naics == -1)]
    mismatches = students_df[(students_df.school_id == 0)]
    if len(mismatches) > 0:
        warn(f"There are {len(mismatches)} students with no school_id")
    teachers_df = df[(df.naics != -1) & (df.grade != -1)]
    mismatches = teachers_df[(teachers_df.school_id == 0)]
    if len(mismatches) > 0:
        warn(f"There are {len(mismatches)} teachers with no school_id")
    workers_df = df[(df.grade == -1) & (df.naics != -1)]
    mismatches = workers_df[(workers_df.school_id != 0)]
    if len(mismatches) > 0:
        warn(f"There are {len(mismatches)} workers with a school_id")
    unemp_df = df[(df.grade == -1) & (df.naics == -1)]
    mismatches = unemp_df[(unemp_df.school_id != 0)]
    if len(mismatches) > 0:
        warn(f"There are {len(mismatches)} unemployed agents with a school_id")
    mismatches = df[(df.naics == -1) & (df.grade == -1) & (df.home_geoid != df.work_geoid)]
    if len(mismatches) > 0:
        warn(f"There are {len(mismatches)} unemployed agents with differing home and dest geoids")


@timer
def main():
    args = get_args()
    np.random.seed(args.rseed)

    upop_df = load_upop_feather_files(args.upop_files, args.output)
    process_upop(upop_df, args.output)

    lodes_df = get_lodes_groups(args.lodes_files)
    schools_df = load_schools(args.schools_file)
    # filter out those schools that don't have the same geoid as the home geoids
    schools_df = schools_df[schools_df.geoid.isin(upop_df.home_geoid.unique())]

    if args.up_nt_dt_files:
        workers_df, students_df, schools_df, unemp_df = process_upop_nt_dt(
            args.up_nt_dt_files, upop_df
        )
    else:
        workers_df, students_df, schools_df, unemp_df = generate_nt_dt(
            schools_df, upop_df, lodes_df
        )
        df = pd.concat([workers_df, students_df, unemp_df], ignore_index=True)

    check_flows_correlation(workers_df, lodes_df)

    workers_df.to_pickle("workers_df.pkl")
    students_df.to_pickle("students_df.pkl")
    schools_df.to_pickle("schools_df.pkl")
    unemp_df.to_pickle("unemp_df.pkl")

    allocate_teachers(workers_df, students_df, schools_df)
    teachers_df = workers_df[workers_df.grade != -1].copy()

    check_school_id_correlation(students_df[students_df.school_id != ""], schools_df, "Students")
    check_school_id_correlation(teachers_df, schools_df, "Teachers")
    check_school_geoid_correlation(students_df[students_df.school_id != ""], schools_df, "Students")
    check_school_geoid_correlation(teachers_df, schools_df, "Teachers")

    print_school_counts(students_df, workers_df)

    df = pd.concat([workers_df, students_df, unemp_df], ignore_index=True)

    # reorder the columns so that we have the largest variables first
    df = df[
        [
            "id",
            "home_geoid",
            "work_geoid",
            "naics",
            "household_id",
            "school_id",
            "age",
            "sex",
            "race",
            "travel",
            "veh_occ",
            "grade",
        ]
    ]
    # set the location types
    df.home_geoid = df.home_geoid.astype("int64")
    df.work_geoid = df.work_geoid.fillna(-1).astype("int64")
    df.loc[df.work_geoid == -1, "work_geoid"] = df.home_geoid
    df.naics = df.naics.astype("int16")

    dump_intermediate(df, args.output + "_nt_dt")
    adjust_indexes(df, args.output)

    print("Fields are:\n", df.dtypes, sep="")

    sanity_checks(df)

    print_cpp_header(df)
    # foffsets, home_pops, home_geoids = print_agents_csv(df, args.output)
    # print_index(df, args.output, foffsets, home_pops, home_geoids)
    foffsets, home_pops, home_geoids = print_agents_bin(df, args.output + "-bin")
    print_index(df, args.output + "-bin", foffsets, home_pops, home_geoids)


if __name__ == "__main__":
    main()
