"""Stage identifiers for KR64 keys: the single source of truth for Python and C++.

Each random decision in population generation is keyed on (seed, replicate, stage, ...). A stage
word is (id << 8) | version: ids are fixed forever, and bumping a stage's version deliberately
changes that stage's random streams without touching any other. `python -m popgen.stages` (run
from utilities/UrbanPop-scripts) regenerates src/PopGenStages.H and the known-answer vectors, so
the two languages cannot drift apart. Never edit the generated header by hand.

The trailing comment on each stage lists the key words that follow (seed, rep, stage).
"""

import os

# name: (id, version, key words after (seed, rep, stage))
STAGES = {
    "PERTURB_TARGET": (1, 1, "puma, constraint, bg"),
    "PERTURB_PRIOR": (2, 1, "puma, donor"),
    "TRS": (3, 1, "bg, k"),
    "CHILDCARE": (4, 1, "bg, h, p"),
    "SLOT_NAICS": (5, 1, "dest_geoid, slot"),
    "SLOT_SIZE": (6, 1, "dest_geoid, slot"),
    "IPF_TRS_ADD": (7, 1, "naics, dest_geoid, k"),
    "IPF_TRS_TRIM": (8, 1, "naics, dest_geoid, home_geoid"),
    "IPF_REPAIR": (9, 1, "naics, home_geoid, sweep, k"),
    "WORK_ASSIGN": (10, 1, "bg, h, p"),
    "WORK_FALLBACK": (11, 1, "bg, h, p"),
    "STU_SCHOOL_PERM": (12, 1, "level, scale, region, school_geoid, school_ord"),
    "STU_SPILL": (13, 1, "level, scale, region, k"),
    "TCH_SCHOOL_PERM": (14, 1, "type, scale, region, school_geoid, school_ord"),
    "TCH_PICK": (15, 1, "type, scale, region, bg, h, p"),
    "TCH_GRADE": (16, 1, "bg, h, p"),
    "HOME_NB": (17, 1, "bg, h"),
    "WG_ORDER": (18, 1, "work_geoid, naics, bg, h, p"),
    "WG_EST_SIZE": (19, 1, "work_geoid, naics, e"),
    "CLASS_SMEAR": (20, 1, "work_geoid, school_geoid, school_ord, grade, rank"),
    "DAY_NB": (21, 1, "day_geoid, kind, a, b, c"),
}


def word(name):
    sid, ver, _ = STAGES[name]
    return (sid << 8) | ver


# Module-level constants, e.g. stages.CHILDCARE.
globals().update({name: word(name) for name in STAGES})

HEADER_PATH = os.path.join(os.path.dirname(__file__), "..", "..", "..", "src", "PopGenStages.H")
VECTORS_PATH = os.path.join(os.path.dirname(__file__), "kr64_vectors.txt")
CDF_VECTORS_PATH = os.path.join(os.path.dirname(__file__), "kr64_cdf_vectors.txt")


def cpp_header():
    ids = [s[0] for s in STAGES.values()]
    assert len(set(ids)) == len(ids), "duplicate stage id"
    lines = [
        "/*! @file PopGenStages.H",
        "    \\brief KR64 stage words for in-process population generation.",
        "",
        "    GENERATED by utilities/UrbanPop-scripts/popgen/stages.py -- do not edit by hand.",
        "    A stage word is (id << 8) | version; see KeyedRNG.H for how keys are built.",
        "*/",
        "#ifndef POPGEN_STAGES_H_",
        "#define POPGEN_STAGES_H_",
        "",
        "#include <cstdint>",
        "",
        "namespace PopGen {",
        "namespace Stage {",
    ]
    for name, (sid, ver, keys) in STAGES.items():
        lines.append(f"constexpr std::int64_t {name} = {word(name)}; // id {sid} v{ver}: {keys}")
    lines += ["} // namespace Stage", "} // namespace PopGen", "", "#endif", ""]
    return "\n".join(lines)


def known_answer_vectors():
    """Lines of `n w1..wn  key  d0 d1 d2  u01_bits  index7 index1000003 index2^40` (decimal)."""
    import numpy as np

    from . import kr64

    tuples = [
        (0,), (1,), (-1,), (0, 0, 0), (42, 0, word("CHILDCARE"), 350010001001, 0, 0),
        (42, 0, word("CHILDCARE"), 350010001001, 0, 1), (42, 1, word("CHILDCARE"), 350010001001, 0, 0),
        (7, 3, word("HOME_NB"), 350490107012, 17), (2**63 - 1,), (-(2**63),),
        (1, 2, 3, 4, 5, 6, 7, 8, 9, 10), (123456789, -987654321), (0, 0, word("TRS"), 60371234001, 99),
        (29, 0, word("IPF_REPAIR"), 111, 350010001001, 11, 5),
        (29, 0, word("SLOT_NAICS"), 350010047001, 0), (29, 0, word("SLOT_NAICS"), 350010047001, 1),
    ]
    tuples += [(i, 0, word("DAY_NB"), 350010001001 + i, 3, i * i, -i, 7) for i in range(16)]
    out = []
    for t in tuples:
        k = kr64.key(*t)
        d = [kr64.draw(k, j) for j in range(3)]
        bits = np.float64(kr64.u01(d[0])).view(np.uint64)
        idx = [int(kr64.index(d[1], n)) for n in (7, 1000003, 2**40)]
        out.append(" ".join([str(len(t))] + [str(w) for w in t] + [str(int(k))]
                            + [str(int(x)) for x in d] + [str(int(bits))] + [str(i) for i in idx]))
    return out


FORMATTER = os.path.join(os.path.dirname(__file__), "..", "..", "custom-clang-format-vscode.py")


def formatted(text):
    """Run the project's clang-format filter (stdin -> stdout), as CLAUDE.md requires for C++."""
    import subprocess
    import sys

    out = subprocess.run([sys.executable, FORMATTER], input=text, capture_output=True, text=True,
                         check=True).stdout
    if not out.strip():
        raise RuntimeError("formatter returned nothing; is clang-format installed?")
    return out


def cdf_vectors():
    """Lines of `kind m w1..wm j result`: kind 0 = int_cdf, 1 = float_cdf (weights as float64 hex),
    each drawn with draw(key(99, 0, j), 0) for j = 0..n-1."""
    import numpy as np

    from . import kr64

    rng = np.random.default_rng(5)  # only to invent test weights; not part of the definition
    out = []
    for m in (1, 2, 3, 7, 50):
        wi = rng.integers(0, 20, m)
        wi[rng.integers(0, m)] += 1  # at least one positive weight
        wf = rng.random(m) * rng.choice([1e-6, 1.0, 1e6])
        for j in range(8):
            x = kr64.draw(kr64.key(99, 0, j), 0)
            out.append(" ".join(["0", str(m)] + [str(int(v)) for v in wi]
                                + [str(j), str(int(kr64.int_cdf(wi, x)))]))
            out.append(" ".join(["1", str(m)] + [float(v).hex() for v in wf]
                                + [str(j), str(int(kr64.float_cdf(wf, x)))]))
    return out


def main():
    with open(HEADER_PATH, "w") as fh:
        fh.write(formatted(cpp_header()))
    with open(VECTORS_PATH, "w") as fh:
        fh.write("\n".join(known_answer_vectors()) + "\n")
    with open(CDF_VECTORS_PATH, "w") as fh:
        fh.write("\n".join(cdf_vectors()) + "\n")
    print("wrote " + ", ".join(os.path.normpath(p) for p in (HEADER_PATH, VECTORS_PATH,
                                                              CDF_VECTORS_PATH)))


if __name__ == "__main__":
    main()
