/*! @file InteractionModelLibrary.H
 * \brief Includes the headers for all available interaction models
 */
#ifndef _INTERACTION_MOD_LIB__H_
#define _INTERACTION_MOD_LIB__H_

#include "InteractionModHH.H"
#include "InteractionModNC.H"
#include "InteractionModNborhood.H"
#include "InteractionModComm.H"
#include "InteractionModSchool.H"
#include "InteractionModWork.H"
#include "InteractionModel.H"

#endif
