# -Wextra-semi: GCC < 10 does not have this.
# -Wunreachable-code: GCC no longer has this option.

name: Linux GCC

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-linux-gcc
  cancel-in-progress: true

jobs:
  # Build ExaEpi
  # Note: this is an intentional "minimal" build that does not enable (many) options
  library:
    name: GNU@11 C++20 Release
    runs-on: ubuntu-24.04
    env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual -Wnon-virtual-dtor -Wlogical-op -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wmissing-include-dirs -Wno-unused-parameter"}
    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies_gcc11.sh
    - name: Build & Install
      run: |
        mkdir build
        cd build
        cmake ..                                  \
            -DCMAKE_VERBOSE_MAKEFILE=ON           \
            -DCMAKE_CXX_STANDARD=20               \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON       \
            -DCMAKE_C_COMPILER=$(which gcc-11)     \
            -DCMAKE_CXX_COMPILER=$(which g++-11)   \
            -DCMAKE_Fortran_COMPILER=$(which gfortran-11)
        make -j 2

  # Build ExaEpi [Debug]
  build_debug:
    name: GNU C++20 Debug
    runs-on: ubuntu-24.04
    env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual -O1 -Wnon-virtual-dtor -Wlogical-op -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wmissing-include-dirs -Wno-unused-parameter"}
      # It's too slow with -O0
    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies.sh
    - name: Build & Install
      run: |
        cmake -S . -B build             \
            -DCMAKE_BUILD_TYPE=Debug    \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DCMAKE_CXX_STANDARD=20     \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON
        cmake --build build -j 2
    - name: Run Tests
      run: |
           source .github/workflows/tests/test_runs.sh 2 1

  # Build ExaEpi
  tests_cxx20:
    name: GNU@11 C++20 OMP
    runs-on: ubuntu-24.04
    env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual -Wextra-semi -Wnon-virtual-dtor -Wlogical-op -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wmissing-include-dirs -Wno-unused-parameter"}
    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies_gcc11.sh
    - name: Build & Install
      run: |
        mkdir build
        cd build
        cmake ..                        \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DAMReX_ASSERTIONS=ON       \
            -DAMReX_TESTING=ON          \
            -DAMReX_BOUND_CHECK=ON      \
            -DAMReX_FPE=ON              \
            -DAMReX_OMP=ON              \
            -DCMAKE_CXX_STANDARD=20                     \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON             \
            -DCMAKE_C_COMPILER=$(which gcc-11)           \
            -DCMAKE_CXX_COMPILER=$(which g++-11)         \
            -DCMAKE_Fortran_COMPILER=$(which gfortran-11)
        make -j 2
    - name: Run Tests
      run: |
           source .github/workflows/tests/test_runs.sh 1 4

  # Build ExaEpi w/o MPI
  tests-nonmpi:
    name: GNU@11 C++20 NOMPI
    runs-on: ubuntu-24.04
    env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual -Wnon-virtual-dtor -Wlogical-op -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wmissing-include-dirs -Wno-unused-parameter"}
    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: .github/workflows/dependencies/dependencies_gcc11_nompi.sh
    - name: Build & Install
      run: |
        mkdir build
        cd build
        cmake ..                        \
            -DCMAKE_BUILD_TYPE=Release  \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DAMReX_ASSERTIONS=ON       \
            -DAMReX_TESTING=ON          \
            -DAMReX_BOUND_CHECK=ON      \
            -DAMReX_FPE=ON              \
            -DAMReX_MPI=OFF             \
            -DCMAKE_CXX_STANDARD=20               \
            -DCMAKE_CXX_STANDARD_REQUIRED=ON       \
            -DCMAKE_C_COMPILER=$(which gcc-11)     \
            -DCMAKE_CXX_COMPILER=$(which g++-11)   \
            -DCMAKE_Fortran_COMPILER=$(which gfortran-11)
        make -j 2
